
[[sec_3]]
== Reference to Recommended Practices

[[sec_3.1]]
=== Reference to Core Document [242-PAS]

This document is an extension of the joint PDM-IF / MBx-IF / JT-IF Recommended Practices
for AP[underline]##242 Domain## Model [underline]##P##roduct and [underline]##A##ssembly
[underline]##S##tructure. Definitions of templates and XML elements contained in
the core document are not repeated here.

Where necessary, references to sections of the core document are given in this format:

[align=center]
[242-PAS] 4.6.7

This means a reference to the Recommended Practices for AP242 Domain Model Product
and Assembly Structure, section 4.6.7.

This Recommended Practices for AP242 Edition 3 Domain Model XML Kinematics are built
on the following version of the core document:

[align=center]
*Version 3.2; dated 2024-01-11*

This document is publicly available from the CAx-IF and JT-IF web pages.

[[sec_3.2]]
=== Listing of Recommended Practices Version in Exchange Files

For validation purposes, STEP processors shall state which Recommended Practice document
and version thereof have been used in the creation of the STEP file. This will not
only indicate what information a consumer can expect to find in the file, but even
more importantly where to find it in the file.

This shall be done by adding a pre-defined string to the first string element of
the `Documentation` attribute of the `Header` element in the XML file (for details
see section [242-PAS] 4.1.5). The value follows a specific pattern well established
in Part 21 files:

[source%unnumbered]
----
Document Type---Document Name---Document Version---Publication Date
----

The string corresponding to this version of this document is:

[source%unnumbered]
----
<Documentation>MBx-IF Rec.Pracs.---AP242 Domain Model
XML Kinematics---1.2---2024-01-11</Documentation>
----

*_General Postprocessor Recommendation:_*

If a postprocessor encounters attribute values, or object instantiations different
from the ones recommended in this version of the document, a warning shall be recorded.
In such case, an additional exchange agreement is supposed to be in place among the
parties involved in the data exchange.
