[[cls-3]]
== Reference to Recommended Practices

For validation purposes, STEP processors shall state which Recommended Practice document
and version thereof have been used in the creation of the STEP file. This will not only
indicate what information a consumer can expect to find in the file, but even more importantly
where to find it in the file.

This shall be done by adding a pre-defined string to the first string element of the
`Documentation` attribute of the `Header` element in the XML file (for details see
<<cls-4.1.5>> below). The value follows a specific pattern well established in Part 21 files:

`Document Type---Document Name---Document Version---Publication Date`

The string corresponding to this version of this document is:

[source%unnumbered]
----
{{{*<Documentation>MBx-IF Rec.Pracs.---AP242 Domain Model XML*}}}
{{{*Assembly Structure---3.2---2024-01-11</Documentation>*}}}
----

*General Postprocessor Recommendation:*

If a postprocessor encounters attribute values, or object instantiations different from the
ones recommended in this version of the document, a warning shall be recorded. In such case, an
additional exchange agreement is supposed to be in place among the parties involved in the
data exchange.
