
[[sec-4]]
== ((Part Structure and Relationships))

The STEP PDM Schema supports explicit hierarchical product structures representing
assemblies and the constituents of those assemblies. This explicit part structure
corresponds to the traditional engineering and manufacturing bill of material indentured
parts list. Relationships between part view definitions are the principle elements
used to structure an explicit part assembly configuration. The relationship itself
represents a specific _usage occurrence_ of the constituent part definition within
the immediate parent assembly definition. Mechanisms to represent quantity associated
with this assembly-component usage relationship are also provided.

The PDM Schema also has the capability to identify and track a specified usage of
a component definition in an assembly at a higher level than the immediate parent
subassembly. Consider a wheel-axle subassembly composed of one axle and two wheels,
the right and the left. A higher-level chassis assembly is in turn composed of two
wheel-axle subassemblies, the front and the rear. The requirement to individually
identify the left-front wheel, for example, is supported by this capability.

Different view definitions of the same version of a part may participate in different
explicit product structures. For example, a design/as-planned view of a particular
version of a part, representing the design discipline part definition, may be engaged
in an explicit design assembly structure. A manufacturing/as-built view of the same
part version represents the definitional template for the actual physical part, and
may participate in a manufactured assembly structure that is different from the design
assembly structure. Finally, a support/as-maintained view of the part version representing
the physical part definition may participate in yet another different disassembly
structure.

In addition to hierarchical assembly structures, the STEP PDM Schema supports relationships
between parts to characterize explicit alternates and substitutes for the assembly.
Other relationships between part definitions exist to characterize the make from
relationship and for supplied part identification.

=== ((Explicit Assembly Bill Of Material))

The STEP PDM Schema supports explicit hierarchical assembly structures representing
assemblies and the constituents of those assemblies. A constituent of an assembly
may itself also be an assembly (a subassembly), which in turn is made up of constituents.
Detail components make up the leaves of these hierarchical part structures.
This explicit part structure corresponds to the traditional engineering and manufacturing
bill of material parts list.

Each individual node in this hierarchy is represented by a part master identification.
The relationships are made between product_definition entities representing a view
definition of the part master. The relationship itself represents the usage occurrence
of a constituent definition within the immediate parent assembly definition. In the
simplest form, this structure corresponds to a basic indentured parts list (see <<fig-2>>).

[[fig-2]]
.Basic Indentured Part List
image::figure-2.svg[]

Each node in the assembly structure breakdown is a part master identification, representing
the definitional template for the part. The nodes in the product structure each have
a corresponding entry in the part list, with indenture level corresponding to depth
in the structure.

==== The Instance Model: EXPRESS entities and attributes

The EXPRESS entities and attributes used to support the requirements of basic explicit
assembly structure are shown in <<diam-20>>.

[[diam-20]]
.Explicit Assembly Instance Diagram
image::diam-20.svg[]

[[sec-4.1.1.1]]
===== ((assembly_component_usage))
(((assembly_component_usage)))

This entity represents the general relationship between two part master identifications,
one a definition of a component and the other a definition of the parent assembly.
This entity is normally not recommended to be instantiated as itself, but is typically
instantiated as the subtype next_assembly_usage_occurrence. This subtype represents
a unique individual occurrence of the component definition as used within the parent
assembly. The assembly_component_usage is only instantiated as itself if there is
an explicit requirement to represent the general relationship between a component
and an assembly definition.

*_Attributes_*

* The *_id_* attribute provides a unique identifier for the relationship.

* The *_name_* attribute provides a general nomenclature for the relationship.

* The *_description_* attribute allows for additional text that further may describe
the relationship.

* The *_relating_product_definition_* attribute is a reference to the parent assembly.

* The *_related_product_definition_* attribute is a reference to the constituent
of the assembly.

* The *_reference_designator_* attribute is optional.

[cols="3",options="header,unnumbered"]
|===
| ENTITY assembly_component_usage | Attribute Population | Remarks

| id | type: identifier = string
| Should be unique in combination with a given relating (parent) and related (child)
product_definition.
| name                        | type: label = string              |
| description                 | type: text = string               | OPTIONAL
| relating_product_definition | type: entity = product_definition | reference to assembly
| related_product_definition  | type: entity = product_definition | reference to component
| reference_designator        | type: identifier = string         | OPTIONAL
|===

*_Preprocessor Recommendations:_* No cyclic product_definition_relationship structures
may be defined. The value of the id attribute must be unique in combination with
the same relating assembly and related component definitions. It is generally recommended
that only subtypes of assembly_component_usage be instantiated. It is not recommended
to instantiate the optional reference_designator attribute for an instance of
assembly_component_usage. In an assembly_component_usage, the attribute reference_designator
may be instantiated with a string of reference designators used for that component
in the assembly. If information on the assembly type is to be represented, then the
name attribute of the product_definition referenced via relating_product_definition
should be used. Examples of such type information are 'functional assembly',
'manufacturing assembly', and 'design assembly'.

*_Postprocessor Recommendations:_* When importing an instance of assembly_component_usage
as itself, postprocessors should interpret this as representing the general assembly-component
relationship.

*_Related Entities:_* None specified.

[[sec-4.1.1.2]]
===== ((next_assembly_usage_occurrence))
(((next_assembly_usage_occurrence)))

This entity is a subtype of assembly_component_usage. It represents a single individual
occurrence of a component definition as used in an immediate next higher parent assembly.
The id attribute contains a unique instance identifier for the individual component
occurrence.

*_Preprocessor Recommendations:_* No cyclic product_definition_relationship structures
may be defined. The value of the id attribute must be unique between the same assembly
and component definitions. The name attribute may be used to record the item find
number corresponding to the particular instance of the component as called out on
an engineering drawing. It is recommended the description attribute contain an instance
display name label for the usage occurrence, if one exists. The reference designator
attribute is optional: it may be used to represent a positional designation for the
component within the assembly.

For AP214 compatibility, preprocessors may generate an instance of product_definition_context_association
to relate a product_definition representing an assembly to a product_definition_context
named 'assemblydefinition'. The presence of such an additional context named
'assembly definition' indicates that the product_definition has component structure
provided beneath it within the STEP exchange file, i.e., it is referenced as relating
in an assembly_component_usage relationship.

NOTE: this information is inherent in the exchange file -- in general it may be obtained
by simply traversing the product structure provided in the file.

*_Postprocessor Recommendations:_* When importing an instance of next_assembly_usage_occurrence
as itself, postprocessors should interpret this to represent a single individual
usage occurrence of the component definition within the parent assembly definition.

*_Related Entities:_* None specified.

====== The Instance Model: STEP exchange file format (<<ISO_10303,part=21>> syntax)

[[ex-16]]
.exchange file for explicit assembly
[source]
--
/* primary application context and life cycle stage */
#10 = APPLICATION_CONTEXT('mechanical design');
#220 = PRODUCT_CONTEXT('', #10, '');
#230 = PRODUCT_DEFINITION_CONTEXT('part definition', #10, 'design');

/* optional AP214 specific characterization for assembly definition */
#340 = PRODUCT_DEFINITION_CONTEXT_ROLE('part definition type', $);
#350 = PRODUCT_DEFINITION_CONTEXT('assembly definition', #10, '');
#520 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#460, #350, #340);

/* type discriminator for part as product */
#100 = PRODUCT_RELATED_PRODUCT_CATEGORY('part', $, (#380, #440));

/* part master for component definition */
#360 = PRODUCT_RELATED_PRODUCT_CATEGORY('detail', $, (#380));
#380 = PRODUCT('g1', 'gasket', $, (#220));
#390 = PRODUCT_DEFINITION_FORMATION('A','',#380);
#400 = PRODUCT_DEFINITION('gv1', 'design view on gasket', #390, #230);

/* part master for assembly definition */
#420 = PRODUCT_RELATED_PRODUCT_CATEGORY('assembly', $, (#440));
#440 = PRODUCT('s1', 'sleeve assembly', $, (#220));
#450 = PRODUCT_DEFINITION_FORMATION('A','',#440);
#460 = PRODUCT_DEFINITION('sv1', 'design view on sleeve assembly', #450, #230);

/* single usage occurrence of component defn within assembly defn */
#530 = NEXT_ASSEMBLY_USAGE_OCCURRENCE('gu1', 'single instance usage', 'gasket usage 1', #460, #400, $);
--

[[sec-4.1.2]]
==== ((Quantified Component Usage))

The basic explicit assembly represents a single occurrence of the component definition
within the assembly definition. Multiple occurrences of a constituent used in an
assembly are represented in two ways in the PDM Schema:

* quantified usage occurrence,

* multiple individual usage occurrences.

The quantified usage occurrence associates a quantity with the component usage, but
does not allow independent identification of individual occurrences when a component
definition is used multiple times.

The PDM Schema uses separate single usage occurrences to represent multiple occurrences
of a component within an assembly when the various components must be distinguished
individually (see <<sec-4.1.3>>).

The quantified usage occurrence associates a quantity value with the multiple use
of a component definition in the parent assembly definition. The quantified usage
occurrence simply relates a quantity value with the multiple component occurrences;
it does not distinguish the individual occurrences independently. The quantified
usage occurrence is most commonly used for standard component parts, such as fasteners,
that need to be quantified but do not need to be individually distinguished.
This structure corresponds to a basic indentured parts list with the associated part
quantity values (see <<fig-3>>).

[[fig-3]]
.Indentured Parts List with Associated Quantity
image::figure-3.svg[]

As with the basic indentured parts list, each node in the part structure breakdown
is a part master, representing the definitional template for the component or assembly.
The nodes of the product structure each have a corresponding entry in the part list,
with the indenture level corresponding to depth in the assembly structure. The quantity
of each usage occurrence is identified in the parts list - the single occurrence
usage has an implicit quantity of one. In this example, the relationship between
the gasket component definition and the parent sleeve subassembly is represented
by a quantified component usage to denote two occurrences of the gasket definition
used in the parent sleeve subassembly.

===== The Instance Model: EXPRESS entities and attributes

The EXPRESS entities and attributes used to support the requirements for quantified
assembly structure are shown in <<diam-21>>.

[[diam-21]]
.Quantified Assembly Instance Diagram
image::diam-21.svg[]

===== ((quantified_assembly_component_usage))
(((quantified_assembly_component_usage)))

This entity is a subtype of assembly_component_usage. When the quantified_assembly_component_usage
is required, it should be created as an AND instantiation with the next_assembly_usage_occurrence.
It adds the attribute quantity to identify the number of occurrences of the constituent
definition that are used in the parent assembly. With the quantified_assembly_component_usage,
multiple individual occurrences of the constituent part are not distinguished independently.

*_Attributes_*

* The *_quantity_* attribute gives the number of usage occurrences of a component
within an assembly.

[cols="3",options="header,unnumbered"]
|===
| ENTITY quantified_assembly_component_usage | Attribute Population | Remarks

| id                          | see supertype                    |
| name                        | see supertype                    |
| description                 | see supertype                    | OPTIONAL
| relating_product_definition | see supertype                    | reference to assembly
| related_product_definition  | see supertype                    | reference to component
| reference_designator        | see supertype                    | OPTIONAL should not be instantiated
| quantity                    | type: entity = measure_with_unit |
|===

*_Preprocessor Recommendations:_* This entity should be instantiated when quantities
greater than one need to be represented, but when the individual occurrences do not
need to be independently distinguished. This is created as a "complex" instance of
next_assembly_usage_occurrence AND quantified_assembly_component_usage. For a quantity
of one, a simple instance of next_assembly_usage_occurrence alone may be used. However,
quantified_assembly_component_usage needs to be used if the number of occurrences
is specified by a specific unit, e.g., the usage of "one liter of oil" as a component
in an assembly.

*_Postprocessor Recommendations:_* When importing an instance of next_assembly_usage_occurrence
AND quantified_assembly_component_usage, a quantity value of one should be interpreted
as equivalent to the simple next_assembly_usage_occurrence.

*_Related Entities:_* None specified.

====== The Instance Model: STEP exchange file format (<<ISO_10303,part=21>> syntax)

[[ex-17]]
.exchange file for quantified component usage
[source]
--
/* primary application context and life cycle stage */
#10 = APPLICATION_CONTEXT('mechanical design');
#220 = PRODUCT_CONTEXT('', #10, '');
#230 = PRODUCT_DEFINITION_CONTEXT('part definition', #10, 'design');

/* type discriminator for part as product */
#100 = PRODUCT_RELATED_PRODUCT_CATEGORY('part', $, (#380, #440));

/* part master for component definition */
#360 = PRODUCT_RELATED_PRODUCT_CATEGORY('detail', $, (#380));
#380 = PRODUCT('g1', 'gasket', $, (#220));
#390 = PRODUCT_DEFINITION_FORMATION('A','',#380);
#400 = PRODUCT_DEFINITION('gv1', 'design view on gasket', #390, #230);

/* part master for assembly definition */
#420 = PRODUCT_RELATED_PRODUCT_CATEGORY('assembly', $,(#440));
#440 = PRODUCT('s1', 'sleeve assembly', $, (#220));
#450 = PRODUCT_DEFINITION_FORMATION('A','',#440);
#460 = PRODUCT_DEFINITION('sv1', 'design view on sleeve assembly', #450, #230);

/* quantified multiple use occurrence of component within assembly */
#860 = DIMENSIONAL_EXPONENTS(0.0E+000, 0.0E+000, 0.0E+000, 0.0E+000, 0.0E+000, 0.0E+000, 0.0E+000);
#870 = NAMED_UNIT(#860);
#880 = MEASURE_WITH_UNIT(COUNT_MEASURE(2), #870);
#890 = (ASSEMBLY_COMPONENT_USAGE($) NEXT_ASSEMBLY_USAGE_OCCURRENCE()
PRODUCT_DEFINITION_RELATIONSHIP('guQgum', 'quantified instance usage',
'quantified usage of gasket', #460, #400) PRODUCT_DEFINITION_USAGE() QUANTIFIED_ASSEMBLY_COMPONENT_USAGE(#880));
--

====== Illustrated Example: Parts Lists and Item Find Number

The following example illustrates the mechanical drawing and corresponding parts
list for two typical example assembly parts, PCA A and PCA B. Each drawing illustrates
the use of the item find number.

[[fig-4]]
.Illustrated example of drawings, associated parts lists, and item find numbers
image::figure-4.svg[]

.Parts list for PCB A
[cols="5",options="header"]
|===
| Find number | Part number | Description | Remarks | Quantity

| 90  | con1001 | Connector |       | 1
| 91  | scr2101 | Screw     |       | 3
| 92  | mem801  | Memory    | U1,U2 | 2
|     |         |           |       |
| ……. |         |           |       |
|===

.Parts list for PCB B
[cols="5",options="header"]
|===
| Find number | Part number | Description | Remarks | Quantity

| 13  | res225 | Resistor |    | 1
| 14  | mem801 | Memory   | U1 | 1
| ... |        |          |    |
|===

In the example above, the same component (part number mem801) is used in both assemblies
PCB A and PCB B. However, the item find number is different for each assembly.
The item find number assigns to the component a name that is specific to the assembly
in which it is being used. In the PDM Schema, the item find number may be assigned
to the name attribute of next_assembly_usage_occurrence.

ISO 6433-1981 has the concept called "item references". This concept is simply the
callout of a component on an assembly drawing via a number which is identified by
the same number in the parts list. The find number is a unique identifier when multiple
uses relationships (such as to Quantified_Assembly_Component_Usage) are created.
For example, when quantities vary by effectivity, a find number is required.
The "Find Number" on the relationship "lists parts masters" between the parts lists
document and the component.

The drawing find number is used to identify components in drawings. Similarly drawing
find number assigns to the component a name that is specific to a drawing in which
the component is being used. The mapping of drawing find number or item reference
should be between the drawing or drawing parts list and the component. The concept
of 'drawing find number' should not be mapped to next_assembly_usage_occurrence.name
between the assembly and the component but should be used in the relationship between
the component and the drawing of the assembly.

In the PDM Schema the item find number may be assigned to the name attribute of
next_assembly_usage_occurrence. The same attribute should be used if the part occurrence
is instantiated as quantified_assembly_component_usage.

[[sec-4.1.3]]
==== ((Multiple Individual Component Occurrences))

The basic explicit assembly represents a single occurrence of the component definition
within the assembly definition. Multiple occurrences of a constituent used within
an assembly are represented in one of two ways in the PDM Schema:

* quantified usage occurrence,

* multiple individual usage occurrences.

The quantified usage occurrence identifies the component quantity, but does not allow
independent identification of the individual occurrences when a component definition
is used multiple times (see <<sec-4.1.2>>).

The PDM Schema uses separate single usage occurrences to represent multiple occurrences
of a component within an assembly when the various components must be distinguished
individually. Multiple occurrences of a component within an assembly must be individually
identified to allow separate ids, display names, reference designation, or related
property information, including shape and orientation/transformation information.

For example, consider a component that is a flexible pipe. The geometrical representation
assigned to the definition of that component may be a simple I shaped tube. The geometrical
representation associated with one occurrence of the pipe positioned in a parent
assembly may be an S shape, as constrained by the assembly environment. A second
occurrence of the pipe definition may be used in the same parent assembly, but in
a different position. The geometrical representation assigned to this occurrence
may be an L shape due to different constraints from the different position of the
component within the parent assembly.

This structure corresponds to a basic indentured parts list with the associated part
quantity values where the individual component occurrences are individually identified
(see <<fig-5>>).

[[fig-5]]
.Indentured Parts List with Multiple Individual Components
image::figure-5.svg[]

===== The Instance Model: EXPRESS entities and attributes

The EXPRESS entities and attributes used to support the requirements of individually
distinguished occurrences of a constituent in an assembly structure are illustrated
in <<diam-22>>.

[[diam-22]]
.Multiple Individual Component Usage Instance Diagram
image::diam-22.svg[]

*_Preprocessor Recommendations:_* The entity next_assembly_usage_occurrence
(see <<sec-4.1.1.2>>) should be instantiated once for each individual occurrence
of a component definition used in the parent assembly. The value of the attribute
id must be unique for each instance. The description attribute may contain a unique
display name for presentation of the assembly structure.

*_Postprocessor Recommendations:_* The sum of single instances of next_assembly_usage_occurrence
that exist between an assembly definition and a component definition represents the
total quantity of component occurrences used in the parent assembly.

*_Related Entities:_* None specified.

===== The Instance Model: STEP exchange file format (<<ISO_10303,part=21>> syntax)

[[ex-18]]
.exchange file for multiple individual component usages
[source]
--
/* primary application context and life cycle stage */
#10 = APPLICATION_CONTEXT('mechanical design');
#220 = PRODUCT_CONTEXT('', #10, '');
#230 = PRODUCT_DEFINITION_CONTEXT('part definition', #10, 'design');

/* optional AP214 specific characterization for assembly definition */
#340 = PRODUCT_DEFINITION_CONTEXT_ROLE('part definition type', $);
#350 = PRODUCT_DEFINITION_CONTEXT('assembly definition', #10, '');
#520 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#460, #350, #340);

/* type discriminator for part as product */
#100 = PRODUCT_RELATED_PRODUCT_CATEGORY('part', $, (#380, #440));

/* part master for component definition */
#360 = PRODUCT_RELATED_PRODUCT_CATEGORY('detail', $, (#380));
#380 = PRODUCT('g1', 'gasket', $, (#220));
#390 = PRODUCT_DEFINITION_FORMATION('A','',#380);
#400 = PRODUCT_DEFINITION('gv1', 'design view on gasket', #390, #230);

/* part master for assembly definition */
#420 = PRODUCT_RELATED_PRODUCT_CATEGORY('assembly', $, (#440));
#440 = PRODUCT('s1', 'sleeve assembly', $, (#220));
#450 = PRODUCT_DEFINITION_FORMATION('A','',#440);
#460 = PRODUCT_DEFINITION('sv1', 'design view on sleeve assembly', #450, #230);

/* multiple single occurrences of component defn in assembly defn */
#530 = NEXT_ASSEMBLY_USAGE_OCCURRENCE('gu-1', 'single instance usage',
'gu1 left', #460, #400, $);
#540 = NEXT_ASSEMBLY_USAGE_OCCURRENCE('gu-2', 'single instance usage', 'gu2 right', #460, #400, $);
--

[[sec-4.1.4]]
==== ((Promissory Component Usage))

The STEP PDM Schema supports promissory usage relationships between components and
some higher-level assembly that is not the immediate parent in the hierarchy.
This may be important to relate an outsourced component to a top-level assembly definition
related to a configuration and product_concept. A supplier may only require the configuration
and end item identification that is associated with the component of interest, and
may not need to know the detailed assembly structure in between. The promissory component
usage may be useful during early design phases to create preliminary BOMs for prototyping.

===== The Instance Model: EXPRESS entities and attributes

The EXPRESS entities and attributes used to support the requirements of promissory
assembly are illustrated in <<diam-23>>.

[[diam-23]]
.Promissory Assembly Usage Instance Diagram
image::diam-23.svg[]

===== ((promissory_usage_occurrence))
(((promissory_usage_occurrence)))

This entity is a subtype of assembly_component_usage. It represents the usage occurrence
of a component within a higher-level assembly that is not the immediate parent, in
the case where the detailed assembly structure in between the component and the higher-level
assembly is not represented. A promissory_usage_occurrence specifies the intention
to use the constituent in an assembly. It may also be used when the product structure
is not completely defined.

*_Preprocessor Recommendations:_* The higher-level assembly should be associated
with a configuration item with its related end item identification in the typical
usage case for the promissory_usage_occurrence. If the assembly structure between
the component and the higher-level assembly must be specified, the next_assembly_usage_occurrence
should be used (see <<sec-4.1.1.2>>).

*_Postprocessor Recommendations:_* None specified.

*_Related Entities:_* None specified.

===== The Instance Model: STEP exchange file format (<<ISO_10303,part=21>> syntax)

[[ex-19]]
.exchange file for promissory assembly usage
[source]
--
/* primary application context and life cycle stage */
#10 = APPLICATION_CONTEXT('mechanical design');
#220 = PRODUCT_CONTEXT('', #10,'');
#230 = PRODUCT_DEFINITION_CONTEXT('part definition', #10, 'design');

/* optional AP214 specific characterization for assembly definition */
#340 = PRODUCT_DEFINITION_CONTEXT_ROLE('part definition type', $);
#350 = PRODUCT_DEFINITION_CONTEXT('assembly definition', #10, '');
#520 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#460, #350, #340);

/* type discriminator for part as product */
#100 = PRODUCT_RELATED_PRODUCT_CATEGORY('part', $, (#380, #440));

/* part master for component definition */
#360 = PRODUCT_RELATED_PRODUCT_CATEGORY('detail', $, (#380));
#380 = PRODUCT('g1', 'gasket', $, (#220));
#390 = PRODUCT_DEFINITION_FORMATION('A','',#380);
#400 = PRODUCT_DEFINITION('gv1', 'design view on gasket', #390, #230);

/* part master for top level assembly definition */
#420 = PRODUCT_RELATED_PRODUCT_CATEGORY('assembly', $, (#440));
#440 = PRODUCT('h1', 'hub assembly', $, (#220));
#450 = PRODUCT_DEFINITION_FORMATION('A','',#440);
#460 = PRODUCT_DEFINITION('hv1', 'design view on hub assembly', #450, #230);

/* promissory usage occurrence of component in top level assembly */
#530 = PROMISSORY_USAGE_OCCURRENCE('pu-1', 'promissory instance usage', 'pu-1 promissory', #460, #400, $);
--

=== ((Multi-Level Assembly Digital Mock Up))

STEP has the capability to identify individual occurrences of component in a multi-level
assembly (see <<sec-4.1.3>>). This provides the ability to assign to each occurrence
an identifier, a position in the assembly, a geometrical representation, or other
properties that may be different from that assigned to the part definition of the
component.

In order to distinguish a specific occurrence of a component in an assembly of more
than two hierarchical levels, the specified_higher_usage_occurrence entity is used.
For example, a wheel-axle subassembly is composed of an axle and two wheels, the
right and the left. A higher-level chassis assembly is in turn composed of two wheel-axle
subassemblies, the front and the back. The requirement to individually identify the
left-front wheel, for example, is supported by this capability.

From the previous wheel-axle-chassis example, an instance of specified_higher_usage_occurrence
is used to represent the left-front wheel. The related_product_definition attribute
references the product_definition that represents the part definition of the component
wheel. The relating_product_definition attribute references the product_definition
representing the definition of the higher-level chassis assembly. The attribute next_usage
is a reference to the next_assembly_usage_occurrence that represents the left wheel
occurrence in the wheel-axle subassembly. The attribute upper_usage is a reference
to the next_assembly_usage_occurrence representing the front occurrence of the wheel-axle
subassembly within the higher-level chassis assembly.

This structure corresponds to an indentured parts list with associated part quantity
values and individual identification of the specific component occurrences used within
a multi-level assembly (see <<fig-6>>).

[[fig-6]]
.Indentured Parts List with Specified Higher Component Usage
image::figure-6.svg[]

In <<fig-6>>, the specific higher usage cu-1 of the cylinder (c-1 in a sleeve subassembly)
within the rear sleeve (su-1 in a hub assembly) of the higher-level hub assembly
is illustrated. Also illustrated is the right gasket (gu2 within a sleeve subassembly)
within the front sleeve (su-2 within a hub assembly) of the higher-level hub assembly,
individually identified as gu-2b. Each specified higher usage occurrence of the gasket,
as well as that of the cylinder, would be individually identified using the same
mechanism as illustrated for the rear cylinder and the front right gasket.

==== The Instance Model: EXPRESS entities and attributes

The EXPRESS entities and attributes used to support the requirements of explicit
multi-level assemblies and digital mockup are illustrated in <<diam-24>>.

[[diam-24]]
.Multi-level Assembly DMU Instance Diagram
image::diam-24.svg[]

===== ((specified_higher_usage_occurrence))
(((specified_higher_usage_occurrence)))

This entity is a subtype of assembly_component_usage. This entity represents the
specific use occurrence within a higher-level assembly of an individual occurrence
of a component definition used in an immediate parent sub-assembly.

[example]
a wheel-axle subassembly is composed of an axle and two wheels, the right and the
left. A higher-level chassis assembly is in turn composed of two wheel-axle subassemblies,
the front and the back. One specific higher usage of the left wheel occurrence within
the higher-level chassis assembly is in the front wheel-axle subassembly (other is
in the rear). The specified_higher_usage_occurrence entity represents the individually
identified left-front wheel. A second instance of this entity could represent another
specified higher usage occurrence of the wheel, for example left rear or right front.

In addition to inherited attributes, this entity defines the attributes next_usage
and upper_usage to relate a single usage occurrence at one level in the assembly
hierarchy (the next_usage) to a single usage occurrence at the next higher level
in the assembly (the upper usage).

In the case of a specified usage occurrence at more than one higher level in the
assembly hierarchy, the upper_usage attribute will reference the specified_higher_usage
instance representing the specified occurrence at the higher level. In this way,
instances of specified_higher_usage_occurrence are "chained" together to identify
specific occurrences of components in an assembly hierarchy with an arbitrary number
of levels.

*_Attributes_*

* The *_next_usage_* attribute identifies the single usage occurrence at a given
level in the hierarchy.

* The *_upper_usage_* attribute identifies the specific higher usage occurrence one
level up in the hierarchy.

[cols="3",options="header,unnumbered"]
|===
| ENTITY specified_higher_usage_occurrence | Attribute Population | Remarks

| id                          | see supertype |
| name                        | see supertype |
| description                 | see supertype | OPTIONAL
| relating_product_definition | see supertype |
| related_product_definition  | see supertype |
| reference_designator        | see supertype | OPTIONAL
| next_usage                  | type: entity = next_assembly_usage_occurrence |
| upper_usage | type: entity = assembly_component_usage
(next_assembly_usage_occurrence OR specified_higher_usage_occurrence)
| References specified_higher_usage_occurrence in the case of a specified usage at
more than one higher level in the hierarchy
|===

*_Preprocessor Recommendations:_* This entity should be instantiated once for each
specific use in a higher-level assembly of an individual occurrence of a component
definition used in a parent assembly. The value of the attribute id must be unique
for each instance. The description attribute may contain a unique display name for
presentation of the assembly structure.

*_Postprocessor Recommendations:_* None specified.

*_Related Entities:_* None specified.

====== The Instance Model: STEP exchange file format (<<ISO_10303,part=21>> syntax)

[[ex-20]]
.exchange file for multi-level assembly DMU
[source]
--
/* primary application context and life cycle stage */
#10 = APPLICATION_CONTEXT('mechanical design');
#220 = PRODUCT_CONTEXT('', #10, '');
#230 = PRODUCT_DEFINITION_CONTEXT('part definition', #10, 'design');

/* optional AP214 specific characterization for assembly definitions */
#340 = PRODUCT_DEFINITION_CONTEXT_ROLE('part definition type', $);
#350 = PRODUCT_DEFINITION_CONTEXT('assembly definition', #10, '');
#520 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#460, #350, #340);
#530 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#660, #350, #340);

/* type discriminator for part as product */
#100 = PRODUCT_RELATED_PRODUCT_CATEGORY('part', $, (#380, #680, #440, #640));

/* part master for component definitions */
#360 = PRODUCT_RELATED_PRODUCT_CATEGORY('detail', $, (#380, #680));
#380 = PRODUCT('g1', 'gasket', $, (#220));
#390 = PRODUCT_DEFINITION_FORMATION('A','',#380);
#400 = PRODUCT_DEFINITION('gv1', 'design view on gasket', #390, #230);
#680 = PRODUCT('c1', 'cylinder', $, (#220));
#690 = PRODUCT_DEFINITION_FORMATION('A','',#680);
#700 = PRODUCT_DEFINITION('cv1', 'design view on cylinder', #690, #230);

/* part master for sub-assemly definition */
#420 = PRODUCT_RELATED_PRODUCT_CATEGORY('assembly', $, (#440, #640));
#440 = PRODUCT('s1', 'sleeve assembly', $, (#220));
#450 = PRODUCT_DEFINITION_FORMATION('A','',#440);
#460 = PRODUCT_DEFINITION('sv1', 'design view on sleeve assembly', #450, #230);

/* part master for higher level hub assembly definition */
#640 = PRODUCT('h1', 'hub assembly', $, (#220));
#650 = PRODUCT_DEFINITION_FORMATION('A','',#640);
#660 = PRODUCT_DEFINITION('hv1', 'design view on hub assembly', #650, #230);

/* single occurrence of component (cylinder) in subassembly defn */
#520 = NEXT_ASSEMBLY_USAGE_OCCURRENCE('cu-1', 'single instance usage', 'cu1', #460, #700, $);

/* multiple single occurrences of component (gasket) in subassembly */
/* the left gasket in a sleeve subassembly */
#530 = NEXT_ASSEMBLY_USAGE_OCCURRENCE('gu-1', 'single instance usage', 'gu1 left', #460, #400, $);

/* the right gasket in a sleeve subassembly */
#540 = NEXT_ASSEMBLY_USAGE_OCCURRENCE('gu-2', 'single instance usage', 'gu2 right', #460, #400, $);

/* multiple single occurrences of subassembly defn in assembly defn */
/* the rear sleeve subassembly in a hub assembly */
#550 = NEXT_ASSEMBLY_USAGE_OCCURRENCE('su-1', 'single instance usage', 'su1 rear', #660, #460, $);

/* the front sleeve subassembly in a hub assembly */
#560 = NEXT_ASSEMBLY_USAGE_OCCURRENCE('su-2', 'single instance usage', 'su2 front', #660, #460, $);

/* specified usage of individual components in higher level assembly */
/* the right gasket in the front sleeve subassembly */
#570=SPECIFIED_HIGHER_USAGE_OCCURRENCE('gu-2b','singleinstance usage', 'gu2b front right', #660, #400, $, #560, #540);

/* the cylinder in the rear sleeve subassembly */
#580=SPECIFIED_HIGHER_USAGE_OCCURRENCE('cu-1','singleinstance usage', 'cu1 rear', #660, #700, $, #550, #520);
--

=== ((Different Views on Assembly Structure))

Different view definitions of the same version of a part may participate in different
explicit product structures in the PDM Schema. For example, a design/as-planned view
of a particular version of a part, representing the design discipline part definition,
may be engaged in an explicit design assembly structure. A manufacturing/as-built
view of the same part version represents the definitional template for the actual
physical part, and may participate in a manufactured assembly structure different
from the design structure. Finally, a support/as-maintained view of the part version
representing the physical part definition that may participate in yet another different
disassembly structure. <<fig-7>> illustrates two different views on a part structure.

[[fig-7]]
.Different Views on Assembly Structure
image::figure-7.svg[]

Many of the parts that make up the 'nodes' in the two different assembly structures
in <<fig-7>> have the same base identification - they simply have multiple definitions
from different life-cycle viewpoints. The disc with holes, the cap, and the sleeve
sub-assembly are all present in both views of the part structure. However, in this
example there is also a new 'node' in the disassembly structure. It corresponds to
a sub-assembly, composed of a disc with holes and a cap, which was not present in
the assembly structure (see <<fig-8>>).

[[fig-8]]
.Different Indentured Lists Corresponding to Different Structure Views
image::figure-8.svg[]

==== The Instance Model: EXPRESS entities and attributes

The EXPRESS entities and relationships that support the requirements of alternate
life-cycle viewpoints on product structure are the same as those already described
for part structures. Recall that the structural element of the part master 'node'
is the product_definition entity, representing a view definition of a part version.
The previous description presumed that each part master element in the assembly structure
had a consistent life-cycle view definition - a single assembly structure from a
single view definition context.

In this example of multiple part structures, the part master information corresponding
to the 'nodes' disc with holes and cap (and sleeve sub-assembly plus its components)
each has two part view definitions. One view definition may represent, for example,
the design or manufactured assembly structure; the other a maintenance or disposal
disassembly structure. Both of the view definitions are related to the same part
version. In this way, the information that is common across the different part structures
(the base version identification for all 'nodes' that have definition in both structures)
is represented only once. Information that is different between the different views,
such as associated management data, property information, or in this case product
structure itself is managed independently by using different product_definitions.

The assembly structure would be constructed between the product_definition instances
that represent the part view definitions within the same appropriate view context,
say for example design.

The disassembly structure would also be constructed between product_definition instances
representing part view definitions within one appropriate life-cycle stage - but
a different one, for example maintenance. Present only in the disassembly structure,
the new or "phantom" part is a sub-assembly composed of a disc with holes and a cap
- it is not present in the assembly structure. The part master information corresponding
to this discap sub-assembly need only have a single part view definition in the appropriate
life-cycle stage, e.g., maintenance. The complete disassembly structure is constructed
using this product_definition, along with those of the other component part masters
for that same view context.

==== The Instance Model: STEP exchange file format (<<ISO_10303,part=21>> syntax)

[[ex-21]]
.exchange file for different assembly and disassembly structures
[source]
--
/* primary application context for design assembly life cycle */
#10 = APPLICATION_CONTEXT('mechanical design');
#220 = PRODUCT_CONTEXT('', #10, '');
#230 = PRODUCT_DEFINITION_CONTEXT('part definition', #10, 'design');

/* primary application context for maintenance disassembly view */
#110 = APPLICATION_CONTEXT('maintenance planning');
#240 = PRODUCT_DEFINITION_CONTEXT('part definition', #110, 'maintenance');

/* optional AP214 specific characterization for assembly definitions */
#340 = PRODUCT_DEFINITION_CONTEXT_ROLE('part definition type', $);
#350 = PRODUCT_DEFINITION_CONTEXT('assembly definition', #10, '');
#820 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#460, #350, #340);
#830 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#660, #350, #340);

/* type discriminator for part as product */
#100 = PRODUCT_RELATED_PRODUCT_CATEGORY('part', $, (#380, #680, #440, #640));
#360 = PRODUCT_RELATED_PRODUCT_CATEGORY('detail', $, (#380, #680));
#420 = PRODUCT_RELATED_PRODUCT_CATEGORY('assembly', $, (#440, #640));

/* part master for common components, each with two view definitions */

/* part master for disc with holes - two view definitions */
#380 = PRODUCT('d1', 'disc with holes', $, (#220));
#390 = PRODUCT_DEFINITION_FORMATION('A','',#380);
#400 = PRODUCT_DEFINITION('dvd1', 'design view on disc', #390, #230);
#410 = PRODUCT_DEFINITION('mvd1', 'maintenance view on disc', #390, #240);

/* part master for cap component - two view definitions */
#680 = PRODUCT('cap1', 'cap for hub', $, (#220));
#690 = PRODUCT_DEFINITION_FORMATION('A','',#680);
#700 = PRODUCT_DEFINITION('dvc1', 'design view on cap', #690, #230);
#710 = PRODUCT_DEFINITION('mvc1', 'maintenance view on cap', #690, #240);

/* part master for "phantom" sub-assembly definition - one view only */
#440 = PRODUCT('p1', 'hubcap subassembly', $, (#220));
#450 = PRODUCT_DEFINITION_FORMATION('A','',#440);
#460 = PRODUCT_DEFINITION('mvp1', 'maintenance view hubcap disassembly', #450, #240);

/* part master for higher level hub assembly - two view definitions */
#640 = PRODUCT('h1', 'hub assembly', $, (#220));
#650 = PRODUCT_DEFINITION_FORMATION('A','',#640);
#660 = PRODUCT_DEFINITION('dvh1', 'design view on hub assembly', #650, #230);
#670 = PRODUCT_DEFINITION('mvh1', 'maintenance view on hub assembly', #650, #240);

/* design life cycle 'as planned' assembly structure */
/* single occurrence of component (disc) defn in hub assembly defn */
#520 = NEXT_ASSEMBLY_USAGE_OCCURRENCE('d-1', 'single instance usage', 'du-1', #660, #400, $);

/* single occurrence of component (cap) defn in hub assembly defn */
#530 = NEXT_ASSEMBLY_USAGE_OCCURRENCE('c-1', 'single instance usage', 'cu-1', #660, #700, $);

/* maintenance life cycle planned disassembly structure */
/* single "phantom" hubcap subassembly occurrence in hub disassembly */
#560 = NEXT_ASSEMBLY_USAGE_OCCURRENCE('hc-1', 'single instance usage', 'hc-1', #670, #460, $);

/* single occurrence of component (disc) defn in hubcap sub-assembly */
#540 = NEXT_ASSEMBLY_USAGE_OCCURRENCE('d-1', 'single instance usage', 'du-1', #460, #410, $);

/* single occurrence of component (cap) defn in hubcap sub-assembly */
#550 = NEXT_ASSEMBLY_USAGE_OCCURRENCE('c-1', 'single instance usage', 'cu-1', #460, #710, $);
--

=== ((Relating Part Shape Properties to Product Structure))

The PDM Schema allows linking geometric structures that result from relating different
shape_representations with associated product structure when applicable, i.e., when
the geometric structure directly corresponds to the assembly structure.

Two alternatives for the implementation of geometric structures related to assembly
structures are recommended:

. The assembly is described with the components built in. With this approach the
shape of the component is mapped into the shape of the assembly via mapped_item.
The basic idea of the mapped_item is: an item will become part of another item. The
assembly component geometry is used as a template in the assembly geometry.

. The components of an assembly are described together with the construction history.
This approach uses the above-described representation_relationship_with_transformation.
The transformation describes the relation between different workspaces.

The usage of both alternatives is considered reasonable, because both mechanisms
make sense even in mixed combinations. With regard to the transformations in the
context of assembly, a part is in principle incorporated in the assembly only by
rigid motion (i.e., translation and/or rotation) excluding mirroring and scaling.

==== ((Explicit Representation of Complete Assembly Geometry))

This approach represents the assembled model completely. It is appropriate for explicit
representation of assemblies. It uses _mapped_item_ in combination with _representation_map_,
which takes a representation and turns it into an item in a second representation.
The transformation to be applied is determined from the mapping origin and the mapping
target, which are items in the two representations (and therefore founded in the
two contexts).

_Mapped_item_ is constrained such that:

* No mapped item shall be dependent on itself to define the representation being
mapped (a cyclic).

* The mapping origin shall be in the context of the mapping_source representation.

There is no constraint to prevent both representations having the same context (i.e.,
the new item is shifted in position but does not change spaces). This allows the
use of _mapped_item_ to position sub-models in a single coordinate space. It is even
possible to define an identity matrix transformation by referring to the same entity
instance as both mapping_origin and mapping_target. This represents the case where
a component is defined in (one of) its final position(s). Until it is mapped into
the second representation, it is not included in the representation even though defined
in the same space.

===== The Instance Model: EXPRESS entities and attributes

The EXPRESS entities and attributes used to support the requirements of explicit
representation of assembly structure with associated external geometry model structure
are illustrated in <<diam-25>>.

[[diam-25]]
.Assembly Structure with Component Templates Instance Diagram
image::diam-25.svg[]

===== ((mapped_item))
(((mapped_item)))

The mapped_item allows the use of a representation as a representation_item, e.g.,
it allows for the definition of representation using other representations.
Thus a shape_representation for an assembly component can participate as a template
instance in the definition of the shape of the overall assembly. The representation
is defined by mapped_item.mapping_source.mapped_representation. The mapping is achieved
through an operator that is a mapping of the mapped_item. mapping_source.mapping_origin
onto the mapped_item.mapping_target

*_Attributes_*

* The *_mapping_source_* attribute points to an instance of representation_map that
specifies the to be mapped representation.

* The *_mapping_target_* attribute is an representation_item that defines.

[cols="3",options="header,unnumbered"]
|===
| ENTITY mapped_item | Attribute Population | Remarks

| mapping_source | type: entity = representation_map  |
| mapping_target | type: entity = representation_item |
|===

*_Preprocessor Recommendations_:* None specified.

*_Postprocessor Recommendations:_* None specified.

*_Related Entities:_* None specified.

===== ((representation_map))
(((representation_map)))

*_Attributes_*

* The *_mapping_origin_* attribute.

* The *_mapped_representation_* attribute references the to be mapped representation.

[cols="3",options="header,unnumbered"]
|===
| ENTITY representation_map | Attribute Population | Remarks

| mapping_origin        | type: entity = representation_item | should be an axis_placement in the given context
| mapped_representation | type: entity = representation      |

|===

*_Preprocessor Recommendations_:* None specified.

*_Postprocessor Recommendations:_* None specified.

*_Related Entities:_* None specified.

==== ((Implicit Relationships Between Assembly Components))

This approach represents the components and the set of instructions on how to build
the assembly. This approach is adequate for the implicit representation of assemblies.
Thus, representation_relationship_with_transformation is used to define the relative
positions within an assembly. It does not allow for:

* Inclusion - the decision to create a representation, which brings all the components
together, is left to the receiving system.

* The ability to define a component in one position and then replicate it in the
same space.

The relationships between the assembly and the component on the product_definition
level and the shape_representation level has to be linked through a context_dependent_shape_representation.
This is necessary to distinguish between several occurrences of the same component
within an assembly. According to Part 43 the attributes rep_1 and rep_2 of
representation_relationship_with_transformation are determined as:

rep 1:: is defined as the representation with a context to which the transformation
applies (in other words rep_1 is defined as the representation with a context to
which the transformation can be applied in case of building an assembly representation)
and

rep 2:: is the representation with a context which is the result of the transformation
(in other words rep_2 is defined as the representation with the context into which
the component representation has to be transformed in case of building an assembly
representation).

Based on this definition the attributes of representation_relationship_with_transformation
should be instantiated as follows:

* representation_relationship_with_transformation.rep_1 for the relation to the shape_representation
for the product_definition that is related by assembly_component_usage as related_product_definition
(identifying the component) and

* representation_relationship_with_transformation.rep_2 for the relation to the shape_representation
for the product_definition that is related by assembly_component_usage as relating_product_definition
(identifying the assembly).

Further restrictions are implied by the Part 43 informal proposition on the entity
representation_relationship_with_transformation: When the transformation is an item_defined_transformation,
the ordering of the representations given for the inherited attributes of representation_relationship
shall be consistent with the ordering of the two representation_items given as attributes
of item_defined_transformation. Therefore the following usage of the attributes transform_item_1
and transform_item_2 of item_defined_transformation is recommended:

* item_defined_transformation.transform_item_1 for the relation to the representation_item
(e.g., axis2_placement_3d) for the product_definition that is related by assembly_component_usage
as related_product_definition (identifying the component) and

* item_defined_transformation.transform_item_2 for the relation to the representation_item
(e.g., axis2_placement_3d) for the product_definition that is related by assembly_component_usage
as relating_product_definition (identifying the assembly).

===== The Instance Model: EXPRESS entities and attributes

The EXPRESS entities and attributes used to support the requirements of relating
assemblies and components using item_defined_transformation are illustrated in <<diam-26>>.

[[diam-26]]
.Assembly Structure with Defined Component Relationships (usage of item_defined_transformation)
image::diam-26.svg[]

Another possibility is the definition of the assembly construction history via a
cartesian_transformation_operator. The Part 42 definition of cartesian_transformation_operator
also allows for scaling and mirroring. But scaling and mirroring shall not to be
applied in the context of assemblies. Therefore:

* the scaling value specified by the attribute cartesian_transformation_operator.scale
shall be empty (due to being optional; default scaling is equal 1.0) or shall be
1.0 and

* the determinant of the transformation matrix u (computed from the attributes axis_1,
axis_2 and axis_3 in case of using cartesian_transformation_operator_3d by the function
base_axis) shall equal 1.

===== The Instance Model: EXPRESS entities and attributes

The EXPRESS entities and attributes used to support the requirements of relating
assemblies and components using cartesian_transformation_operator are illustrated
in <<diam-27>>.

[[diam-27]]
.Assembly Structure with Defined Component Relationships (usage of cartesian_transformation_operator)
image::diam-27.svg[]

===== ((context_dependent_shape_representation))
(((context_dependent_shape_representation)))

A context_dependent_shape_representation associates a shape_representation_relationship
with a product_definition_shape. In the given context this allows the explicit specification
of a shape of the assembly 'as assembled'. Since elements when assembled might change
their shape -- e.g., under pressure -- this representation may differ from the geometric
assembly of the individual shapes.

*_Attributes_*

* The *_representation_relation_* attribute is a reference to the shape_representation_relationship
used to define the assembly.

* The *_represented_product_relation_* attribute points to the product_definition_shape
that is related to the assembly_usage_occurrence.

[cols="3",options="header,unnumbered"]
|===
| ENTITY context_dependent_shape_representation | Attribute Population | Remarks

| representation_relation      | type: entity = shape_representation_relationship |
| represented_product_relation | type: entity = product_definition_shape          |
|===

*_Preprocessor Recommendations:_* None specified.

*_Preprocessor Recommendations:_* None specified.

*_Related Entities:_* None specified.

==== ((Complete instantiation example for part structure with shape properties))

The example file contains two independent products. One part is an assembly of two
components ('part 1' and part 2'). For this product structure a corresponding relationship
that geometrically relates the components with the assembly is defined. It is assumed
that the geometry is defined in external files. For 'part 2' this external file constitutes
a managed document that is associated to the focused view of the part. For
'part 1' the external geometry is linked in via an external file for which no revision
control exists. Such a flat file association for external geometry would be typical
for files directly received from CAD systems.

[[fig-9]]
.Schematic Overview of Complete Part Structure with Shape Properties
image::figure-9.svg[]

For the third part in the file two portions of shape are represented and identified
independently. For these portions a geometric relationship is defined. This geometric
relationship has no correspondence in product structure.

[[fig-10]]
.Schematic Overview of Geometric Relationship
image::figure-10.svg[]

===== The Instance Model: STEP exchange file format (<<ISO_10303,part=21>> syntax)

[[ex-22]]
.complete instantiation for part structure with shape properties
[source]
--
ISO-10303-21; HEADER;
FILE_DESCRIPTION((''), '2;1');
FILE_NAME('', '30.06.1999, 12:05:33', ('N:N:'), (''), '', '', '');
FILE_SCHEMA(('PDM_SCHEMA {1.2}')); ENDSEC;
DATA;

/* Entities #10 to #350 describe meta information and product structure */

#10 = APPLICATION_CONTEXT('');
#20 = PRODUCT_CONTEXT('', #10, '');
#30 = PRODUCT('ass', 'assembly', '', (#20));
#40 = PRODUCT_RELATED_PRODUCT_CATEGORY('assembly', $, (#30));
#50 = PRODUCT_RELATED_PRODUCT_CATEGORY('part', '', (#30));
#60 = PRODUCT_CATEGORY_RELATIONSHIP('', $, #50, #40);
#70 = PRODUCT('p', 'part', '', (#20));
#80 = PRODUCT('p1', 'part1', '', (#20));
#90 = PRODUCT('p2', 'part2', '', (#20));
#100 = PRODUCT_RELATED_PRODUCT_CATEGORY('part', '', (#30, #80, #90, #70));
#110 = APPLICATION_PROTOCOL_DEFINITION('version 1.2', 'pdm_schema', 2000 , #10);
#120 = PRODUCT_DEFINITION_CONTEXT_ROLE('', $);
#130 = PRODUCT_DEFINITION_CONTEXT('part definition', #10, '');
#140 = PRODUCT_DEFINITION_FORMATION('1', '', #30);
#150 = PRODUCT_DEFINITION('assv', 'view on assembly', #140, #130);
#160 = APPLICATION_CONTEXT('mechanical design');
#170 = PRODUCT_DEFINITION_CONTEXT('', #160, 'design');
#180 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#150, #170, #120);
#190 = PRODUCT_RELATED_PRODUCT_CATEGORY('Detail', $, (#80, #90, #70));
#200 = PRODUCT_RELATED_PRODUCT_CATEGORY('Part', '', (#80, #90, #70));
#210 = PRODUCT_CATEGORY_RELATIONSHIP('', $, #200, #190);
#220 = PRODUCT_DEFINITION_FORMATION('1', '', #80);
#230 = PRODUCT_DEFINITION('p1v', 'view on part1', #220, #130);
#240 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#230, $, #120);
#250 = PRODUCT_DEFINITION_FORMATION('1', '', #70);
#260 = PRODUCT_DEFINITION('p', 'view on part', #250, #130);
#270 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#260, $, #120);
#280 = PRODUCT_DEFINITION_FORMATION('1', '', #90);
#290 = PRODUCT_DEFINITION('p2v', 'view on part2', #280, #130);
#300 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#290, $, #120);
#310 = NEXT_ASSEMBLY_USAGE_OCCURRENCE('p1_usage', 'single instance usage', '', #150, #230, $);
#320 = PRODUCT_DEFINITION_CONTEXT_ROLE('part definition type', $);
#330 = PRODUCT_DEFINITION_CONTEXT('assembly definition', #10, '');
#340 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#150, #330, #320);
#350 = NEXT_ASSEMBLY_USAGE_OCCURRENCE('p2_usage', 'single instance usage', '', #150, #290, $);

/* Entities #370 to #497 define a managed document which */
/* contains a representation of the shape of 'part2' */
#370 = PRODUCT('p2_shape_doc', 'document reflecting shape of part2', '', (#20));
#380 = PRODUCT_RELATED_PRODUCT_CATEGORY('document', '', (#370));
#390 = DOCUMENT_TYPE('configuration controlled document version');
#400 = DOCUMENT('', '', '', #390);
#410 = APPLIED_DOCUMENT_REFERENCE(#400, 'equivalence', (#290));
#420 = OBJECT_ROLE('mandatory', '');
#430 = ROLE_ASSOCIATION(#420, #410);
#440 = PRODUCT_DEFINITION_FORMATION('1', '', #370);
#450 = DOCUMENT_PRODUCT_EQUIVALENCE('equivalence', '', #400, #440);
#460 = PRODUCT_DEFINITION_CONTEXT('digital document definition', #10, '');
#470 = PRODUCT_DEFINITION_WITH_ASSOCIATED_DOCUMENTS('p2_shape_d', 'digital document for part2 shape', #440, #460,(#475));
#475 = DOCUMENT_FILE('p2_shape_file', '', '', #485, '', $);
#480 = DOCUMENT_REPRESENTATION_TYPE('digital',#475);
#485 = DOCUMENT_TYPE('');
#490 = IDENTIFICATION_ROLE('document_source',$);
#495 = APPLIED_EXTERNAL_IDENTIFICATION_ASSIGNMENT('',#490,#497,(#475));
#497 = EXTERNAL_SOURCE(IDENTIFIER('part1_geometry.stp'));

/* Entities #500 to #560 define the geometric model for 'part1' */
#500 = PRODUCT_DEFINITION_SHAPE('shape_p1',$,#230);
#510 = SHAPE_DEFINITION_REPRESENTATION(#500,#520);
#520 = SHAPE_REPRESENTATION('sol1',(#570),#530);
#530 = GEOMETRIC_REPRESENTATION_CONTEXT('c1','external',3);
#540 = CARTESIAN_POINT('', (1.0E+001, 0.0E+000, 1.0E+001));
#550 = DIRECTION('', (0.0E+000, -1.0E+000, 0.0E+000));
#560 = DIRECTION('', (1.0E+000, 0.0E+000, 0.0E+000));
#570 = AXIS2_PLACEMENT_3D('', #540, #550, #560);

/* Entities #575 to #585 state that the shape_representation #520 */
/* is externally defined in a digital file with the location */
/* 'part2_geometry.stp'*/

#575 = APPLIED_DOCUMENT_REFERENCE(#576,'',(#230));
#576 = DOCUMENT_FILE('p1_shape','',$,#577,'', $);
#577 = DOCUMENT_TYPE('geometry');
#578 = ROLE_ASSOCIATION(#579,#575);
#579 = OBJECT_ROLE('mandatory',$);
#580 = DOCUMENT_REPRESENTATION_TYPE('digital',#576);
#581 = IDENTIFICATION_ROLE('document_source',$);
#582 = APPLIED_EXTERNAL_IDENTIFICATION_ASSIGNMENT('',#581,#583,(#576));
#583 = EXTERNAL_SOURCE(IDENTIFIER('part2_geometry.stp'));
#584 = PROPERTY_DEFINITION('external definition',$,#576);
#585 = PROPERTY_DEFINITION_REPRESENTATION(#584,#520);

/* Entities #600 to #660 define the geometric model for 'part2' */
#600 = PRODUCT_DEFINITION_SHAPE('shape_p2',$,#290);
#610 = SHAPE_DEFINITION_REPRESENTATION(#600,#620);
#620 = SHAPE_REPRESENTATION('sol2',(#670),#630);
#630 = GEOMETRIC_REPRESENTATION_CONTEXT('c2','external',3);
#640 = CARTESIAN_POINT('', (3.0E+001, 0.0E+000, 1.0E+001));
#650 = DIRECTION('', (0.0E+000, -1.0E+000, 0.0E+000));
#660 = DIRECTION('', (1.0E+000, 0.0E+000, 0.0E+000));
#670 = AXIS2_PLACEMENT_3D('', #640, #650, #660);

/* Entities #680 and #690 indicate that the shape_representation #620 */
/* is externally defined by the file represented by #475 */

#680 = PROPERTY_DEFINITION('external definition',$,#475);
#690 = PROPERTY_DEFINITION_REPRESENTATION(#680,#620);

/* Entities #700 to #720 defines the shape and two related portions */
/* for the part 'part' #260*/
#700 = PRODUCT_DEFINITION_SHAPE('shape_p',$,#260);
#710 = SHAPE_ASPECT('aspect1',$,#700,.T.);
#720 = SHAPE_ASPECT('aspect2',$,#700,.T.);

/* Entities #730 to #790 define the geometry related to */
/* shape_aspect #710*/
#730 = PROPERTY_DEFINITION('shape for aspect1',$,#710);
#740 = SHAPE_DEFINITION_REPRESENTATION(#730,#750);
#750 = SHAPE_REPRESENTATION('sa1',(#795),#760);
#760 = GEOMETRIC_REPRESENTATION_CONTEXT('ca1','external',3);
#770 = CARTESIAN_POINT('', (3.0E+001, 0.0E+000, 1.0E+001));
#780 = DIRECTION('', (0.0E+000, -1.0E+000, 0.0E+000));
#790 = DIRECTION('', (1.0E+000, 0.0E+000, 0.0E+000));
#795 = AXIS2_PLACEMENT_3D('', #770, #780, #790);

/* the link to the external definition in a file has been omitted here */
/* Entities #800 to #860 define the geometry related to */
/* shape_aspect #720*/
#800 = PROPERTY_DEFINITION('shape for aspect2',$,#720);
#810 = SHAPE_DEFINITION_REPRESENTATION(#800,#820);
#820 = SHAPE_REPRESENTATION('sa2',(#870),#830);
#830 = GEOMETRIC_REPRESENTATION_CONTEXT('ca2','external',3);
#840 = CARTESIAN_POINT('', (3.0E+001, 0.0E+000, 1.0E+001));
#850 = DIRECTION('', (0.0E+000, -1.0E+000, 0.0E+000));
#860 = DIRECTION('', (1.0E+000, 0.0E+000, 0.0E+000));
#870 = AXIS2_PLACEMENT_3D('', #840, #850, #860);

/* the link to the external definition in a file has been omitted here */
/* #1000 and #1010 establish the relationship between the */
/* geometry of the two shape_aspects */
#1000 = (REPRESENTATION_RELATIONSHIP('','',#750,#820) REPRESENTATION_RELATIONSHIP_WITH_TRANSFORMATION(#1010) SHAPE_REPRESENTATION_RELATIONSHIP());
#1010 = ITEM_DEFINED_TRANSFORMATION('aspect_rel','',#795,#870);

/* #1050 to #1140 define the geometric representation of */
/* the assembly (#150). The shape_representation contains */
/* two axis_placements that are the reference points for */
/* the transformations of the components */
#1050 = PRODUCT_DEFINITION_SHAPE('shape_of_ass',$,#150);
#1060 = SHAPE_DEFINITION_REPRESENTATION(#1050,#1070);
#1070 = SHAPE_REPRESENTATION('s_assembly',(#1110,#1140),#1080);
#1080 = GEOMETRIC_REPRESENTATION_CONTEXT('ca','',3);
#1090 = CARTESIAN_POINT('', (3.0E+001, 4.0E+000, 1.0E+001));
#1095 = DIRECTION('', (1.0E+000, 0.0E+000, 0.0E+000));
#1100 = DIRECTION('', (0.0E+000, -1.0E+000, 0.0E+000));
#1110 = AXIS2_PLACEMENT_3D('', #1090, #1095, #1100);
#1120 = CARTESIAN_POINT('', (1.0E+001, 1.0E+000, 1.0E+001));
#1125 = DIRECTION('', (1.0E+000, 0.0E+000, 0.0E+000));
#1130 = DIRECTION('', (0.0E+000, -1.0E+000, 0.0E+000));
#1140 = AXIS2_PLACEMENT_3D('', #1120, #1125, #1130);

/* Entities #1200 to #1230 define the geometric relationship */
/* between the component 'part1' and the assembly #150. This */
/* relationship is linked to the product structure relationship */
/* defined by the next_assembly_usage_occurrence #310 */
#1200 = PRODUCT_DEFINITION_SHAPE('shape of assembled p1',$,#310);
#1210 = CONTEXT_DEPENDENT_SHAPE_REPRESENTATION(#1220,#1200);
#1220 =(REPRESENTATION_RELATIONSHIP('','',#520,#1070) REPRESENTATION_RELATIONSHIP_WITH_TRANSFORMATION(#1230) SHAPE_REPRESENTATION_RELATIONSHIP());
#1230 = ITEM_DEFINED_TRANSFORMATION('p1t','',#1110,#570);

/* Entities #1300 to #1330 define the geometric relationship */
/* between the component 'part2' and the assembly #150. This */
/* relationship is linked to the product structure relationship */
/* defined by the next_assembly_usage_occurrence #350 */
#1300 = PRODUCT_DEFINITION_SHAPE('shape of assembled p2',$,#350);
#1310 = CONTEXT_DEPENDENT_SHAPE_REPRESENTATION(#1320,#1300);
#1320 =(REPRESENTATION_RELATIONSHIP('','',#620,#1070) REPRESENTATION_RELATIONSHIP_WITH_TRANSFORMATION(#1330) SHAPE_REPRESENTATION_RELATIONSHIP());
#1330 = ITEM_DEFINED_TRANSFORMATION('p2t','',#1140,#670);

/* Entities #5000 to #5070 assert that the in #290 defined view */
/* of part2 has a mass of 3KG */
#5000 = GENERAL_PROPERTY('mass property', '', '');
#5010 = GENERAL_PROPERTY_ASSOCIATION('non-definitional', '', #5000, #5020);
#5020 = PROPERTY_DEFINITION('', '', #290);
#5030 = PROPERTY_DEFINITION_REPRESENTATION(#5020, #5040);
#5040 = REPRESENTATION('property value', (#5060), #5050);
#5050 = REPRESENTATION_CONTEXT('', '');
#5060 = MEASURE_REPRESENTATION_ITEM('mass', MASS_MEASURE(3000), #5070);
#5070 =(NAMED_UNIT(*) MASS_UNIT() SI_UNIT($,.GRAM.));

ENDSEC;
END-ISO-10303-21;
--

=== ((Other Relationships Between Parts))

==== ((Alternate Parts))

STEP designates alternate and substitute parts differently. Alternate parts are interchangeable
in all occurrences whereas substitutes are interchangeable only in a particular usage.
Alternate parts in STEP are defined through the alternate_product_relationship entity.
This relationship is used in the definition of parts list data for alternate item
designations.

===== The Instance Model: EXPRESS entities and attributes

The EXPRESS entities and attributes used to support the requirements of alternate
part identification are illustrated in <<diam-28>>.

[[diam-28]]
.Alternate Part Instance Diagram
image::diam-28.svg[]

===== ((alternate_product_relationship))
(((alternate_product_relationship)))

This entity represents the alternate part relationship. The alternate part is interchangeable
with the base part in any/all uses - it is a context independent alternate that is
form, fit, and function equivalent in any use.

*_Attributes_*

* The *_name_* attribute has no standard mapping in the PDM Schema.

* The *_definition_* attribute is an optional description.

* The *_base_* attribute is a reference to the primary product of which an alternate
is being identified.

* The *_alternate_* attribute is a reference to the product identified as an alternate
for the base product.

* The *_basis_* attribute is a rationale for the part interchange (e.g., any use,
first available, etc.).

[cols="3",options="header,unnumbered"]
|===
| ENTITY alternate_product_relationship | Attribute Population | Remarks

| name       | type: label = string   |
| definition | type: text = string    | OPTIONAL
| base       | type: entity = product |
| alternate  | type: entity = product |
| basis      | type: text = string    |
|===

*_Preprocessor Recommendations:_* There are no standard mappings for the name and
definition attributes of alternate_product_relationship. The basis attribute should
contain a rationale for the part interchange (e.g. any use, first available, etc.)
if it is known.

*_Postprocessor Recommendations:_* Since there are no standard mappings for the name
and definition attributes of alternate_product_relationship, it is recommended that
postprocessors not assign any general processing significance to these values.

*_Related Entities:_* None specified.

===== The Instance Model: STEP exchange file format (<<ISO_10303,part=21>> syntax)

[[ex-23]]
.exchange file segment for alternate part
[source]
--
/* primary application context for design assembly life cycle */
#10 = APPLICATION_CONTEXT('mechanical design');
#220 = PRODUCT_CONTEXT('', #10, '');
#230 = PRODUCT_DEFINITION_CONTEXT('part definition', #10, 'design');

/* part type discrimination */
#6=PRODUCT_RELATED_PRODUCT_CATEGORY('part',$,(#4, #11));
#7=PRODUCT_CATEGORY_RELATIONSHIP('part-to-detail',$,#6,#8);
#8=PRODUCT_RELATED_PRODUCT_CATEGORY('detail',$,(#4, #11));
#4=PRODUCT('11111','Solid Box','description for part 11111',(#220));
#11=PRODUCT('11011','Solid Cube','description for part 11011',(#12));
#14=ALTERNATE_PRODUCT_RELATIONSHIP('',$,#11,#4,'interchangeable as solid squares');
--

==== ((Substitute Components in an Assembly))

Substitute components in an assembly are identified as a relationship between the
occurrences of two part definitions (the two substitutes) that are used within the
same parent assembly definition. As opposed to the alternate part relationship, which
is context free, this substitute relationship is context dependent - the substitute
is only valid in the context of its usage as a component within the specified parent
assembly definition.

===== The Instance Model: EXPRESS entities and attributes

The EXPRESS entities and attributes used to support the requirements of substitute
part identification are illustrated in <<diam-29>>.

[[diam-29]]
.Substitute Component Instance Diagram
image::diam-29.svg[]

===== ((assembly_component_usage_substitute))
(((assembly_component_usage_substitute)))

This entity represents the substitute component relationship. The substitute part
is interchangeable with the base part only in the particular, specified usage - it
is a context dependent substitution that is allowed only in the specific usage as
the component in the identified component-assembly relationship.

*_Attributes_*

* The *_name_* attribute has no standard mapping in the PDM Schema.

* The *_definition_* attribute is an optional description.

* The *_base_* attribute is a reference to the primary component occurrence of which
a substitute is being identified.

* The *_substitute_* attribute is a reference to the product identified as a substitute
for the base component.

[cols="3",options="header,unnumbered"]
|===
| ENTITY assembly_component_usage_substitute | Attribute Population | Remarks

| name       | type: label = string                    |
| definition | type: text = string                     | OPTIONAL
| base       | type:entity = assembly_component_usage  |
| substitute | type: entity = assembly_component_usage |
|===

*_Preprocessor Recommendations:_* There are no standard mappings for the name and
definition attributes of assembly_component_usage_substitute. The relating_product_definition
for both the base and substitute attributes of this relationship must be the same
instance representing the same assembly definition.

*_Postprocessor Recommendations:_* Since there are no standard mappings for the name
and definition attributes of assembly_component_usage_substitute, it is recommended
that postprocessors not assign any general processing significance to these values.

*_Related Entities:_* None specified.

===== The Instance Model: STEP exchange file format (<<ISO_10303,part=21>> syntax)

[[ex-24]]
.exchange file segment for substitute component
[source]
--
#1330 = PROMISSORY_USAGE_OCCURRENCE('seal_in_sleeve', 'single instance usage', 'promissory usage of sealing for sleeve assembly ver2', #1210, #1300, $);
#1335 = PROMISSORY_USAGE_OCCURRENCE('seal_in_sleeve', 'single instance usage', 'promissory usage of sealing ver 2 for sleeve assembly ver2', #1210, #1305, $);
#1337 = ASSEMBLY_COMPONENT_USAGE_SUBSTITUTE('sealings_alternative_sleeve', $,#1330,#1335);
--

==== ((Make From Relationships))

In STEP, the fact that a part is manufactured from another part is indicated by make_from_usage_option.
The make_from_usage_option relates the source part definition in the related_product_definition
attribute to the resultant part definition in the relating_product_definition attribute.

===== The Instance Model: EXPRESS entities and attributes

The EXPRESS entities and attributes used to support the requirements of make from
part identification are illustrated in <<diam-30>>.

[[diam-30]]
.Make From Relationship Instance Diagram
image::diam-30.svg[]

===== ((make_from_usage_option))
(((make_from_usage_option)))

This entity is a subtype of product_definition_usage. The related_product_definition
represents the raw or semi-finished material, and the relating_product_definition
represents the resultant manufactured item.

*_Attributes_*

* The *_relating_product_definition_* represents the part manufactured from the related_product_definition.

* The *_related_product_definition_* represents the raw or semi-finished material.

* The *_ranking_* attribute is a relative ranking value. A lower value indicates
a higher preference.

* The *_ranking_rationale_* explains the reason for the ranking.

* The *_quantity_* attribute records the number of resultant parts that can be made
from the source part.

[cols="3",options="header,unnumbered"]
|===
| ENTITY make_from_usage_option | Attribute Population | Remarks

| id                          | type: identifier = string         | unique for product data relationship
| name                        | type: label = string              |
| description                 | type: text = string               | OPTIONAL
| relating_product_definition | type: entity = product_definition |
| related_product_definition  | type: entity = product_definition |
| ranking                     | type: integer                     |
| ranking_rationale           | type: text = string               |
| quantity                    | type: entity = measure_with_unit  |
|===

*_Preprocessor Recommendations:_* The id attribute must be unique among product_definition_relationships.
There is no standard mapping for the name or ranking_rationale attributes in a make_from_usage_option.

*_Postprocessor Recommendations:_* Since there is no standard value for the name
and ranking_rationale attributes for a make_from_usage_option, it is recommended
that postprocessors not assign any processing significance to these values.

*_Related Entities:_* None specified.

====== The Instance Model: STEP exchange file format (<<ISO_10303,part=21>> syntax)

[[ex-25]]
.exchange file for make from relationship
[source]
--
/* primary application context for design assembly life cycle */
#1000 = APPLICATION_CONTEXT('mechanical design');
#220 = PRODUCT_CONTEXT('', #1000, '');
#230 = PRODUCT_DEFINITION_CONTEXT('part definition', #1000, 'design');

/* part type discrimination */
#100=PRODUCT_RELATED_PRODUCT_CATEGORY('part',$,(#2, #9));
#2=PRODUCT('11000','solid cube','description for part 11000',(#220));
#3=PRODUCT_DEFINITION_FORMATION('A', 'description of version A for solid cube',#2);
#4=PRODUCT_DEFINITION('D1','detailed drawing as planned for STEP conformance testing',#3,#230);
#9=PRODUCT('11111','Solid Box','part 11111 made from raw material 11000',(#220));
#10=PRODUCT_DEFINITION_FORMATION('A', 'description of version A for part 11111',#9);
#11=PRODUCT_DEFINITION('D2','detailed drawing',#10,#230);
#16=MAKE_FROM_USAGE_OPTION('id','name','make two solid boxes from one solid cube', #11, #4,1,'',#17);
#17 = MEASURE_WITH_UNIT(COUNT_MEASURE(2), #18);
#18 = NAMED_UNIT(#19);
#19 = DIMENSIONAL_EXPONENTS(0.0E+000, 0.0E+000, 0.0E+000, 0.0E+000, 0.0E+000, 0.0E+000, 0.0E+000);
--

[[sec-4.5.4]]
==== ((Supplied Part Identification))

Supplied part identification is realized by an 'alias relationship' concept. It is
specific for supplied parts that allow the renumbering of vendor parts.

In all realms of design and manufacturing business, it is common to buy parts from
a vendor and renumber them under an internal numbering scheme. In today's practice,
this is done through envelope, specification and source control drawings.

* An envelope drawing is used for a simple renumber of a part where the part is referenced
on the envelope drawing and assigned a new part number via the associated parts list.

* A specification control drawing renumbers a part to show that it meets or exceeds
the specifications defined on the drawing and to recommend sources for the part.

* A source control drawing renumbers a part and creates a restricted list of suppliers
that are qualified to produce the part based on the specifications.

All of these relationships are supported by the product_definition_formation_relationship
entity. This entity is used for the identification of part suppliers.
The product_definition_formation_relationship may be used for the renumbering of
parts. The supplied part relationship relates the "new" part master product_definition_formation
in the relating_product_definition_formation attribute to the "old" part master
product_definition_formation in the related_product_definition_formation attribute.

===== The Instance Model: EXPRESS entities and attributes

The EXPRESS entities and attributes essential to support the requirements of supplied
part identification are illustrated in <<diam-31>>.

[[diam-31]]
.Supplied Part Instance Diagram
image::diam-31.svg[]

===== ((product_definition_formation_relationship))
(((product_definition_formation_relationship)))

This entity generally relates two product_definition_formation instances in a specified
relationship type - the identification of the relationship type is given in the name
attribute.

*_Attributes_*

* The *_id_* attribute provides an identifier of the relationship.

* The *_name_* attribute specifies this relationship represents 'supplied item'.

* The *_relating_product_definition_formation_* attribute references the internal
part version information.

* The *_related_product_definition_formation_* attribute references the supplied
part version information.

[cols="3",options="header,unnumbered"]
|===
| ENTITY product_definition_formation_Relationship | Attribute Population | Remarks

| id                                    | type: identifier = string                   |
| name                                  | type: label = string                        | shall be 'supplied item'
| description                           | type: text = string                         | OPTIONAL
| related_product_definition_formation  | type: entity = product_definition_formation | supplied part version information
| relating_product_definition_formation | type: entity = product_definition_formation | internal part version
|===

*_Preprocessor Recommendations:_* The value 'supplied item' for the name attribute
identifies this as the supplied item relationship. There is no standard mapping for
the description attribute in a product_definition_formation_relationship. The id
attribute must be unique with respect to the relationship, but there is no standard
mapping for the value.

*_Postprocessor Recommendations:_* Since there are no standard mapping for the description
attributes for a product_definition_formation_relationship, it is recommended that
postprocessors not assign any processing significance to this value.

*_Related Entities:_* Certification of suppliers can be indicated through the supplied
item relationship. This is done by relating an applied_certification_assignment to
the product_definition_formation_relationship, which associates a certification to
the relationship. The applied_certification_assignment entity may have a role associated
with it through the entity role_association and its related object_role entity. There
are no standard mappings for the values of the role, or the name and purpose attributes
of the certification entity.

====== The Instance Model: STEP exchange file format (<<ISO_10303,part=21>> syntax)

[[ex-26]]
.exchange file for supplied part
[source]
--
/* primary application context for design assembly life cycle */
#1000 = APPLICATION_CONTEXT('mechanical design');
#220 = PRODUCT_CONTEXT('', #1000, '');
#230 = PRODUCT_DEFINITION_CONTEXT('part definition', #1000, 'design');

/* part type discrimination */
#100=PRODUCT_RELATED_PRODUCT_CATEGORY('part',$,(#2, #9));

/* solid cube - supplied part */
#2=PRODUCT('11000','solid cube','description for part 11000',(#220));
#3=PRODUCT_DEFINITION_FORMATION('A', 'description of version A for solid cube',#2);
#4=PRODUCT_DEFINITION('D1','detailed drawing as planned for STEP conformance testing',#3,#230);

/* solid box - internal part */
#9=PRODUCT('11111','Solid Box','part 11111 made from raw material 11000',(#220));
#10=PRODUCT_DEFINITION_FORMATION('A', 'description of version A for part 11111',#9);
#11=PRODUCT_DEFINITION('D2','detailed drawing',#10,#230);
#16=PRODUCT_DEFINITION_FORMATION_RELATIONSHIP('id','supplied item',$,#10,#3);
--

==== ((Version History Relationships))

There are two types of relationships between product versions used to represent the
version history:

* Sequential relationship: The relating part version is the preceding version and
the related part version is the subsequent following version. Both versions must
be associated with the same part master base. A part version may have at most one
preceding and one subsequent following version.

* Hierarchical relationship: The related part version is a sub version of the relating
part version (sometimes referred to as an _iteration_). Both versions must be associated
with the same part master base. Each part version may have at most one super version
(parent in the hierarchy). A part version may have an arbitrary number of sub versions
(children in the hierarchy). Part versions related by hierarchical relationships
may not define cyclic relationships.

===== The Instance Model: EXPRESS entities and attributes

The EXPRESS entities and attributes used to support the requirements of part version
sequence history are illustrated in <<diam-32>>.

[[diam-32]]
.Part Version (sequence) History Instance Diagram
image::diam-32.svg[]

===== ((product_definition_formation_relationship))
(((product_definition_formation_relationship)))

Entity generally relates two product_definition_formation instances in a specified
relationship type - the identification of the relationship type is given in the name
attribute.

*_Attributes_*

* The *_id_* attribute provides an identifier of the relationship.

* The *_name_* attribute specifies this relationship represents a version 'sequence'
or 'hierarchy' history.

* The *_relating_product_definition_formation_* attribute references the preceding
(sequence) or super (hierarchy) part version.

* The *_related_product_definition_formation_* attribute references the subsequent
(sequence) or sub (hierarchy) part version.

[cols="3",options="header,unnumbered"]
|===
| ENTITY product_definition_formation_Relationship | Attribute Population | Remarks

| id                                    | type: identifier = string                   |
| name                                  | type: label = string                        | shall be 'sequence' or 'hierarchy'
| description                           | type: text = string                         | OPTIONAL
| relating_product_definition_formation | type: entity = product_definition_formation | preceding part version
| related_product_definition_formation  | type: entity = product_definition_formation | subsequent part version
|===

*_Preprocessor Recommendations:_* The value 'sequence' for the name attribute identifies
this as the version sequence history relationship. The value 'hierarchy' for the
name attribute identifies this as the version hierarchical relationship. There is
no standard mapping for the description attribute in a product_definition_formation_relationship.
The id attribute must be unique with respect to the relationship, but there is no
standard mapping for the value.

*_Postprocessor Recommendations:_* Since there are no standard mapping for the description
attributes for a product_definition_formation_relationship, it is recommended that
postprocessors not assign any processing significance to this value.

*_Related Entities:_* None specified.

====== The Instance Model: STEP exchange file format (<<ISO_10303,part=21>> syntax)

[[ex-27]]
.exchange file for part version (sequence) history
[source]
--
/* primary application context for design assembly life cycle */
#1000 = APPLICATION_CONTEXT('mechanical design');
#220 = PRODUCT_CONTEXT('', #1000, '');
#230 = PRODUCT_DEFINITION_CONTEXT('part definition', #1000, 'design');

/* part type discrimination */
#100=PRODUCT_RELATED_PRODUCT_CATEGORY('part',$,(#2));

/* version A - preceding version */

#2=PRODUCT('11000','solid cube','description for part 11000',(#220));
#3=PRODUCT_DEFINITION_FORMATION('A', 'version A for solid cube',#2);
#4=PRODUCT_DEFINITION('D1','detailed drawing as planned for STEP conformance testing',#3,#230);

/* version B - subsequent version */
#10=PRODUCT_DEFINITION_FORMATION('B', 'version B for part 11000',#2);
#11=PRODUCT_DEFINITION('D2','detailed drawing',#10,#230);

#16=PRODUCT_DEFINITION_FORMATION_RELATIONSHIP('id','sequence',$,#3,#10);
--

=== ((Complete instantiation example for part structure and relationships))

[[ex-28]]
.exchange file for complete part structure and relationships
[source]
--
ISO-10303-21;
HEADER;
FILE_DESCRIPTION(('Assembly instantiation example'), '2;1'); FILE_NAME('', '11.06.1999, 08:29:45', (''), (''), '', '', ''); FILE_SCHEMA(('PDM_SCHEMA {1.2}'));
ENDSEC;
DATA;

/* Entities #10 to #520 define that items with associated meta-*/
/* information that are referenced in the product structure*/
/* definitions below*/
#10 = APPLICATION_CONTEXT('');
#20 = PRODUCT_CONTEXT('', #10, '');
#30 = PRODUCT('dca', 'disc cap assembly', 'disc cap assembly in dissassembly view of hub assembly', (#20));
#40 = PRODUCT('h1', 'hub assembly', '', (#20));
#50 = PRODUCT('s1', 'sleeve assembly', '', (#20));
#60 = PRODUCT_RELATED_PRODUCT_CATEGORY('assembly', $, (#40, #50, #30));
#70 = PRODUCT_RELATED_PRODUCT_CATEGORY('part', '', (#40, #50, #30));
#80 = PRODUCT_CATEGORY_RELATIONSHIP('', $, #70, #60);
#90 = PRODUCT('seal1', 'sealing', '', (#20));
#100 = PRODUCT('d1', 'disc', 'disc with holes', (#20));
#110 = PRODUCT('c1', 'cap', 'cap for hub assembly', (#20));
#120 = PRODUCT('cy1', 'cylinder', 'cylinder for sleeve assembly', (#20));
#130 = PRODUCT('g1', 'gasket', 'gasket for sleeve assembly', (#20));
#140 = PRODUCT('gex', 'gasket extern', 'externally supplied gasket', (#20));
#150 = PRODUCT('mat23', 'raw material for caps', '', (#20));
#160 = PRODUCT('cl_alt', 'cylinder alternative', 'alternate product for cy1', (#20));
#170 = PRODUCT_RELATED_PRODUCT_CATEGORY('part', '', (#40, #100, #110, #50, #120, #130, #30, #140, #150, #160, #90));
#180 = APPLICATION_PROTOCOL_DEFINITION('version 1.2', 'pdm_schema', 2000, #10);
#190 = PRODUCT_RELATED_PRODUCT_CATEGORY('detail', $, (#100, #110, #120, #130, #140, #160, #90));
#200 = PRODUCT_RELATED_PRODUCT_CATEGORY('part', '', (#100, #110, #120, #130, #140, #160, #90));
#210 = PRODUCT_CATEGORY_RELATIONSHIP('', $, #200, #190);
#220 = PRODUCT_DEFINITION_CONTEXT_ROLE('', $);
#230 = PRODUCT_DEFINITION_CONTEXT('part definition', #10, '');
#240 = PRODUCT_DEFINITION_FORMATION('next_assembly', 'hub assembly version 2 (with individual occurrences of components', #40);
#250 = PRODUCT_DEFINITION('view 1 hub', 'design view on hub assembly', #240, #230);
#260 = APPLICATION_CONTEXT('mechanical design');
#270 = PRODUCT_DEFINITION_CONTEXT('', #260, 'design');
#280 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#250, #270, #220);
#290 = PRODUCT_DEFINITION_FORMATION('1', '', #100);
#300 = PRODUCT_DEFINITION('disc view 1', 'design view on disc', #290, #230);
#310 = APPLICATION_CONTEXT('mechanical design');
#320 = PRODUCT_DEFINITION_CONTEXT('', #310, 'design');
#330 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#300, #320, #220);
#340 = PRODUCT_DEFINITION_CONTEXT_ROLE('part definition type', $);
#350 = PRODUCT_DEFINITION_CONTEXT('assembly definition', #10, '');
#360 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#250, #350, #340);
#370 = NEXT_ASSEMBLY_USAGE_OCCURRENCE('disc1', 'single instance usage', '', #250, #300, $);
#390 = PRODUCT_DEFINITION_FORMATION('1', '', #130);
#400 = PRODUCT_DEFINITION('gv1', 'design view on gasket', #390, #230);
#410 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#400, #270, #220);
#420 = PRODUCT_DEFINITION_FORMATION('1', '', #120);
#430 = PRODUCT_DEFINITION('cv1', 'design view on cylinder', #420, #230);
#440 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#430, #270, #220);
#450 = PRODUCT_DEFINITION_FORMATION('1', '', #50);
#460 = PRODUCT_DEFINITION('sv1', 'design view on sleeve assembly', #450, #230);
#470 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#460, #270, #220);
#480 = PRODUCT_DEFINITION_FORMATION('1', '', #110);
#490 = PRODUCT_DEFINITION('capv1', 'design view on cap', #480, #230);
#500 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#490, #270, #220);
#520 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#460, #350, #340);

/* Instances #530 to #570 define the product structure for*/
/* the hub assembly of #250 via the components including the*/
/* sub-assembly of the sleeve #460 */
#530 = NEXT_ASSEMBLY_USAGE_OCCURRENCE('gu1', 'single instance usage', 'gasket usage 1', #460, #400, $);
#540 = NEXT_ASSEMBLY_USAGE_OCCURRENCE('gu2', 'single instance usage', 'gasket usage 2', #460, #400, $);
#550 = NEXT_ASSEMBLY_USAGE_OCCURRENCE('cyl1', 'single instance usage', 'cylinder usage', #460, #430, $);
#560 = NEXT_ASSEMBLY_USAGE_OCCURRENCE('cap1', 'single instance usage', 'usage of cap in hub assembly', #250, #490, $);
#570 = NEXT_ASSEMBLY_USAGE_OCCURRENCE('svu1', 'single instance usage', 'usage of sleeve sub-assembly in hub assembly', #250, #460, $);

/* Entitles #580 to #700 define the 'id owners' for the parts */
#580 = ORGANIZATION('com1', 'Example Company', 'company');
#590 = ORGANIZATION_ROLE('id_owner');
#600 = APPLIED_ORGANIZATION_ASSIGNMENT(#580, #590, (#40));
#610 = ORGANIZATION_ROLE('id owner');
#620 = APPLIED_ORGANIZATION_ASSIGNMENT(#580, #610, (#130));
#630 = ORGANIZATION_ROLE('id owner');
#640 = APPLIED_ORGANIZATION_ASSIGNMENT(#580, #630, (#120));
#650 = ORGANIZATION_ROLE('id owner');
#660 = APPLIED_ORGANIZATION_ASSIGNMENT(#580, #650, (#50));
#670 = ORGANIZATION_ROLE('id owner');
#680 = APPLIED_ORGANIZATION_ASSIGNMENT(#580, #670, (#110));
#690 = ORGANIZATION_ROLE('id owner');
#700 = APPLIED_ORGANIZATION_ASSIGNMENT(#580, #690, (#100));

/* Entity #710 is an alternate view on the hub assembly version*/
/* defined by the product_definition_formation #240*/
/* The product structure in this view is defined by the entities */
/* #760 to #810*/
/* This product structure is different to the view #240 of the*/
/* same part version defined by #250. In this example the alternate */
/* product structure related to the view is a disassembly structure */
/* as opposed to the assembly structure related to the view #250 */
#710 = PRODUCT_DEFINITION('view 2 hub', 'disassembly view on hub', #240, #230);
#720 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#710, $, #220);
#730 = PRODUCT_DEFINITION_FORMATION('1', '', #30);
#740 = PRODUCT_DEFINITION('dcav1', 'disassembly view on disc and cap', #730, #230);
#750 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#740, $, #220);
#760 = NEXT_ASSEMBLY_USAGE_OCCURRENCE('du', 'single instance usage', 'disc in disc cap assembly', #740, #300, $);
#770 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#740, #350, #340);
#780 = NEXT_ASSEMBLY_USAGE_OCCURRENCE('cu', 'single instance usage', 'cap in disc-cap assembly', #740, #490, $);
#790 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#710, #350, #340);
#800 = NEXT_ASSEMBLY_USAGE_OCCURRENCE('su2', 'single instance usage', 'sleeve assembly in disassembly view of hub', #710, #460, $);
#810 = NEXT_ASSEMBLY_USAGE_OCCURRENCE('dcau1', 'single instance usage', 'disc cap assembly usage in disassembly view of hub', #710, #740, $);

/* #820 is another version of the hub assembly defined by #40*/
/* This version is specified with a product structure that*/
/* quantifies the occurrences of components in an assembly*/
/* The product structure relationships that defines the quantified */
/* usage of the components in an assembly are instantiated complex */
/* with NEXT_ASSEMBLY_COMPONENT_USAGE to indicate that a given*/
/* parent node directly uses the referenced component */
#820 = PRODUCT_DEFINITION_FORMATION('quantif', 'version specified with quantified usages', #40);
#830 = PRODUCT_DEFINITION('qv1', 'view on quantified version of hub assembly', #820, #230);
#840 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#830, $, #220);
#850 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#830, #350, #340);
#860 = DIMENSIONAL_EXPONENTS(0.0E+000, 0.0E+000, 0.0E+000, 0.0E+000, 0.0E+000, 0.0E+000, 0.0E+000);
#870 = NAMED_UNIT(#860);
#880 = MEASURE_WITH_UNIT(COUNT_MEASURE(1), #870);
#890 = (ASSEMBLY_COMPONENT_USAGE($) NEXT_ASSEMBLY_USAGE_OCCURRENCE()
PRODUCT_DEFINITION_RELATIONSHIP('du4', 'quantified instance usage', 'quantified usage of disc', #830, #300) PRODUCT_DEFINITION_USAGE() QUANTIFIED_ASSEMBLY_COMPONENT_USAGE(#880));
#900 = DIMENSIONAL_EXPONENTS(0.0E+000, 0.0E+000, 0.0E+000, 0.0E+000, 0.0E+000, 0.0E+000, 0.0E+000);
#910 = NAMED_UNIT(#900);
#920 = MEASURE_WITH_UNIT(COUNT_MEASURE(1), #910);
#930 = (ASSEMBLY_COMPONENT_USAGE($) NEXT_ASSEMBLY_USAGE_OCCURRENCE() PRODUCT_DEFINITION_RELATIONSHIP('cau4', 'quantified instance usage', 'quantified usage if cap', #830, #490) PRODUCT_DEFINITION_USAGE() QUANTIFIED_ASSEMBLY_COMPONENT_USAGE(#920));
#940 = PRODUCT_DEFINITION_FORMATION('slq', 'quantified version of sleeve assembly', #50);
#950 = PRODUCT_DEFINITION('slqv', 'design view quantified version sleeve assembly', #940, #230);
#960 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#950, $, #220);
#970 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#950, #350, #340);
#980 = DIMENSIONAL_EXPONENTS(0.0E+000, 0.0E+000, 0.0E+000, 0.0E+000, 0.0E+000, 0.0E+000, 0.0E+000);
#990 = NAMED_UNIT(#980);
#1000 = MEASURE_WITH_UNIT(COUNT_MEASURE(1), #990);
#1010 = (ASSEMBLY_COMPONENT_USAGE($) NEXT_ASSEMBLY_USAGE_OCCURRENCE() PRODUCT_DEFINITION_RELATIONSHIP('cu4', 'quantified instance usage', 'quantified usage of cylinder', #950, #430) PRODUCT_DEFINITION_USAGE() QUANTIFIED_ASSEMBLY_COMPONENT_USAGE(#1000));
#1020 = DIMENSIONAL_EXPONENTS(0.0E+000, 0.0E+000, 0.0E+000, 0.0E+000, 0.0E+000, 0.0E+000, 0.0E+000);
#1030 = NAMED_UNIT(#1020);
#1040 = MEASURE_WITH_UNIT(COUNT_MEASURE(2), #1030);
#1050 = (ASSEMBLY_COMPONENT_USAGE($) NEXT_ASSEMBLY_USAGE_OCCURRENCE() PRODUCT_DEFINITION_RELATIONSHIP('gu4', 'quantified instance usage', 'quantified usage of gasket for sleeve', #950, #400) PRODUCT_DEFINITION_USAGE() QUANTIFIED_ASSEMBLY_COMPONENT_USAGE(#1040));

/* #140 represents an externally supplied gasket part*/
/* The relationship #1070 relates the version 1 of this externally */
/* supplied part to the internal part master represented by*/
/* #140 in its version 1 (defined by #390) */
#1060 = PRODUCT_DEFINITION_FORMATION('1', '', #140);
#1070 = PRODUCT_DEFINITION_FORMATION_RELATIONSHIP('', 'supplied item', 'supplied item version of gasket', #1060, #390);
#1080 = ORGANIZATION('com2', 'Supplier Company', 'company');
#1090 = ORGANIZATION_ROLE('id owner');
#1100 = APPLIED_ORGANIZATION_ASSIGNMENT(#1080, #1090, (#1060));

/* product #140 represents the raw material for the cap product */
/* (#110), version 1 (#480) in the design view (#490) */
#1120 = PRODUCT_RELATED_PRODUCT_CATEGORY('raw material', '', (#150));
#1140 = PRODUCT_DEFINITION_FORMATION('1', '', #150);
#1150 = PRODUCT_DEFINITION('mat_view', 'design view on mat23', #1140, #230);
#1160 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#1150, $, #220);
#1170 = ORGANIZATION_ROLE('id owner');
#1180 = APPLIED_ORGANIZATION_ASSIGNMENT(#580, #1170, (#1140));

/* Entities #1181 to #1185 establish the relation that defines that */
/* the cap (in view of #490) is made from the raw material specified */
/* via #1150 and related entities*/
#1181 = DIMENSIONAL_EXPONENTS(0.0E+000, 0.0E+000, 0.0E+000, 0.0E+000, 0.0E+000, 0.0E+000, 0.0E+000);
#1182 = NAMED_UNIT(#1181);
#1184 = MEASURE_WITH_UNIT(COUNT_MEASURE(1), #1182);
#1185 = MAKE_FROM_USAGE_OPTION('mkfr1','','',#490,#1150,1,'',#1184);

/* #1190 models the successor version of the sleeve assembly*/
/* version 1 define by #450. 'Sequence' indicates that #1190 is */
/* a direct successor to #450*/
#1190 = PRODUCT_DEFINITION_FORMATION('2', 'successor version of version 1', #50);
#1200 = PRODUCT_DEFINITION_FORMATION_RELATIONSHIP('', 'sequence', '', #450, #1190);

/* #1210 specifies a view on the sleeve assembly version 2. To this */
/* view a product structure is attached that extends the product*/
/* structure of version one with an additional sealing part */

/* For this sealing no detail is given, a*/
/* promissory_usage_occurrence is used to model the intent to */
/* include the sealing in the sleeve assembly */
#1210 = PRODUCT_DEFINITION('sv2', 'design view on sleeve version 2', #1190, #230);
#1220 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#1210, $, #220);
#1230 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#1210, #350, #340);
#1240 = NEXT_ASSEMBLY_USAGE_OCCURRENCE('gu5', 'single instance usage', 'gasket usage for ver2 of sleeve assembly', #1210, #400, $);
#1250 = NEXT_ASSEMBLY_USAGE_OCCURRENCE('gu6', 'single instance usage', '2ns gasket usage for sleeve assembly ver2', #1210, #400, $);
#1260 = PRODUCT_DEFINITION_FORMATION('1', '', #160);
#1270 = PRODUCT_DEFINITION('v1_cyl_alt', 'design view on alternate cylinder', #1260, #230);
#1280 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#1270, $, #220);
#1290 = PRODUCT_DEFINITION_FORMATION('1', 'sealing ver1', #90);
#1295 = PRODUCT_DEFINITION_FORMATION('2', 'sealing ver2', #90);
#1300 = PRODUCT_DEFINITION('sv1', 'design view on sealing v1', #1290, #230);
#1305 = PRODUCT_DEFINITION('sv2', 'design view on sealing v2', #1295, #230);
#1310 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#1300, $, #220);
#1320 = NEXT_ASSEMBLY_USAGE_OCCURRENCE('cylalt', 'single instance usage' , 'usage of alternate cylinder of sleeve v2', #1210, #1270, $);

/* #1330 models the intent to use the sealing part as defined */
/* by #1300 in the sleeve part as defined by #1210 */
#1330 = PROMISSORY_USAGE_OCCURRENCE('seal_in_sleeve', 'single instance usage', 'promissory usage of sealing for sleeve assembly ver2', #1210, #1300, $);

/* The entities #1335 and #1337 define a usage of another version of */
/* the sealing part given by its view in #1305 in the sleeve*/
/* assembly #1210. #1337 specifies that the usage of the two version */
/* of the sealing in the sleeve assembly is alternative, i.e. the*/
/* product structure relationship defined by #1335 is alternative to */
/* the one defined by #1330*/
#1335 = PROMISSORY_USAGE_OCCURRENCE('seal_in_sleeve', 'single instance usage', 'promissory usage of sealing ver 2 for sleeve assembly ver2', #1210, #1305, $);
#1337 = ASSEMBLY_COMPONENT_USAGE_SUBSTITUTE('sealings_alternative_sleeve', $,#1330,#1335);

/* #1340 is a version of the hub assembly #40 that is derived from */
/* the version #240 of the same part. The derivation relationship is */
/* established by entity #1350*/
#1340 = PRODUCT_DEFINITION_FORMATION('ver_double', 'double sleeve version', #40);
#1350 = PRODUCT_DEFINITION_FORMATION_RELATIONSHIP('', 'derivation', '', #240, #1340);
#1360 = PRODUCT_DEFINITION('dsl_view', 'design view on double sleeve version of hub', #1340, #230);
#1370 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#1360, $, #220);
#1380 = PRODUCT_DEFINITION_CONTEXT_ASSOCIATION(#1360, #350, #340);

/* The assembly structure below assembles the #1340 version of the */
/* hub assembly with 2 sleeves. the sleeves each consist of two */
/* gaskets and one cylinder. Thus in the resulting product */
/* structure there are four cylinders. The basic next_assembly_usage */
/* construct allows only to distinguish between two gaskets one the */
/* level of the sleeve assembly definition. To individualize one of */
/* the gaskets in the hub assembly specified_higer_usage_occurrence */
/* is used.*/
#1390 = NEXT_ASSEMBLY_USAGE_OCCURRENCE('dcau', 'single instance usage', 'usage of dca assembly for double sleeve version', #1360, #740, $);
#1400 = NEXT_ASSEMBLY_USAGE_OCCURRENCE('usl1', 'single instance usage', '1st sleeve in double sleeve version', #1360, #460, $);
#1410 = NEXT_ASSEMBLY_USAGE_OCCURRENCE('usl2', 'single instance usage', '2nd sleeve in double sleeve assembly', #1360, #460, $);

/* #1415 individualizes the first gasket (#530) used in the*/
/* second sleeve (#1410) of the assembly #1360. */
#1415 = SPECIFIED_HIGHER_USAGE_OCCURRENCE('2nd_g', 'identification of second gasket of first sleeve', $,
#1360, /* the hub assembly */
#400, /* gasket used for the assembly */
$, /* reference_designator*/
#1410, /* upper_usage: select the second sleeve usage */
#530 /* next_usage_: select first usage of gasket in sleeve */
);

/* #1420 specifies that the alternate cylinder part #160 is an*/
/* alternative to the cylinder #120. These parts are mutually*/
/* exchangeable in any context*/

#1420 =
ALTERNATE_PRODUCT_RELATIONSHIP('hub_alternativity',$,#160,#120,'text for basis');
ENDSEC;
END-ISO-10303-21;
--

=== ((Known issues))

==== Item Find Number
(((Known issues,Item Find Number)))

Legacy AP203 implementations have used the name attribute of the next_assembly_usage_occurrence
entity to represent the find_number (or position_number) of a part as it appears
on a physical drawing. This conflicts with the AP214 usage of this attribute to distinguish
single instances from selected instances.

==== Mirroring of components
(((Known issues,Mirroring of components)))

Scaling and mirroring shall not be applied in the context of assemblies. However,
it is common practice in CAD systems to use mirror parts. The PDM-IF is planning
to test assemblies with mirror parts. Therefore this issue has to be addressed in
the next release of the PDM Schema Usage Guide.
