== Communication

The MBx-IF provides various of means of communication, in order to keep its members
and associated working groups up to date on current testing activities and agreements.

[[sec-3.1]]
=== Web Sites

The MBx Interoperability Forum maintains an internet homepage, which is mirrored at
three URLs:

* https://www.mbx-if.de/
* https://www.mbx-if.eu/
* https://www.mbx-if.org/

The contents at all locations are identical. Only in the context of updates it may
happen that the sites are out of sync temporarily, depending on the availability of
the respective web master. These pages cover general information about the MBx-IF, as
well as all public information on the CAx, CAE and EWIS domains. This includes
Recommended Practices, Test Suite documents, and information on implementation support.

The PDM has a separate homepage, as it joined the MBx-IF at a later point in time. It
can be found at:

* http://www.pdm-if.org/

In the near future, it is planned to merge all of these web pages into one.

=== Mailing Lists

This section provides an overview on the currently maintained mailing lists.

Note that there currently are no mailing lists for the CAE and EWIS domains.

==== CAx-IF

* cax-contact@lists.purdue.edu -- The AFNeT, PDES, Inc. and prostep ivip facilitators
of the CAx-IF
* cax-current-round@lists.purdue.edu -- Closed mailing list for the active
participants of the current round of CAx testing.
* team-users-cax-if@lists.afnet.fr -- Closed mailing list for the CAx-IF User Group

==== PDM-IF

* implementors@lists.pdm-if.org -- Closed mailing list for the PDM-IF Implementor Group
* users@lists.pdm-if.org -- Closed mailing list for the PDM-IF User Group

=== Meetings

The various teams within the MBx-IF conduct multiple meetings per year. All of these
meetings are set up as hybrid meetings, i.e., presence in person on site is always
preferred, but if not possible, remote attendance will be possible.

==== CAx-IF & EWIS-IF

There are usually four milestone meetings per year, generally following this pattern:

* *March*: Face-to-face meeting in Europe
** CAx-IF and EWIS-IF Test Round Review
** MBx-IF User / Vendor Roundtable
** In conjunction with LOTAR 1^st^ Qtr. WS
* *June*: Online meeting
** CAx-IF and EWIS-IF Test Round Kick-Off
** In conjunction with LOTAR 2^nd^ Qtr. WS
* *September*: Face-to-face meeting in the USA
** CAx-IF and EWIS-IF Test Round Review
** MBx-IF User / Vendor Roundtable
** In conjunction with LOTAR 3^rd^ Qtr. WS
* *December*: Online meeting
** CAx-IF and EWIS-IF Test Round Kick-Off
** In conjunction with LOTAR 4^th^ Qtr. WS

==== PDM-IF

The PDM-IF usually meets face-to-face twice per year, in June and December. These
meetings alternate between France and Germany. They are mainly comprised of Test
Round Review and a joint meeting between the Implementor Group and User Group.

=== Conference Calls

Regular conference calls are set up throughout the year to keep track of each group's
progress. The meeting notices will be sent out by the respective facilitators.

These calls use established conferencing platforms, such as Microsoft Teams, Google
Meet, or WebEx.
